export const searchCopy = {
  open: "Apri la ricerca globale",
  trigger: "Cerca in Hub Fatture",
  title: "Ricerca globale",
  label: "Cerca in ordini, documenti, clienti e attività",
  placeholder: "Ordine, documento, cliente, attività o dato fiscale",
  clear: "Cancella la ricerca",
  startTitle: "Trova subito ciò che ti serve",
  startHelp:
    "Cerca per numero, nome, e-mail, dato fiscale, attività o documento rilevato in Aruba.",
  loading: "Ricerca in corso…",
  errorTitle: "Ricerca momentaneamente non disponibile",
  errorHelp: "Riprova fra qualche istante.",
  emptyTitle: "Nessun risultato",
  emptyHelp: (query: string) =>
    `Nessuna corrispondenza per “${query}”. Controlla il testo e riprova.`,
  results: (count: number) => `${count} ${count === 1 ? "risultato trovato" : "risultati trovati"}`,
  orders: "Ordini",
  invoices: "Fatture",
  creditNotes: "Note di credito",
  customers: "Clienti",
  activities: "Attività da gestire",
  history: "Cronologia",
  remoteDocuments: "Documenti Aruba da collegare",
  order: (provider: string, number: string) =>
    `Ordine ${provider === "SHOPIFY" ? "Shopify" : "eBay"} ${number}`,
  invoice: (number: string) => `Fattura ${number}`,
  invoicePreparation: (number: string) => `Preparazione fattura ${number}`,
  creditNote: (number: string | null) =>
    number ? `Nota di credito ${number}` : "Nota di credito in preparazione",
  remoteDocument: (type: string, number: string) => `${type} ${number}`,
  remoteDocumentWithoutNumber: (type: string) => `${type} rilevato in Aruba`,
  activitySubject: (subject: string | null) => subject ?? "Elemento da verificare",
  historySubject: (subject: string | null) => subject ?? "Operazione registrata",
  viewAll: (label: string, count: number) => `Vedi tutti: ${label} (${count})`,
  issued: "Emessa",
  draft: "In preparazione",
  noContact: "Recapito non disponibile",
  customerOrders: (count: number) => `${count} ${count === 1 ? "ordine" : "ordini"}`,
  keyboardHelp: "Usa Tab per muoverti fra i risultati",
};
