export const controlsCopy = {
  eyebrow: "Lavoro operativo",
  title: "Controlli",
  intro: "Risolvi le decisioni che richiedono il tuo intervento.",
  viewsLabel: "Stato dei controlli",
  open: "Da risolvere",
  waiting: "In attesa",
  severityLabel: "Gravità",
  kindLabel: "Tipo",
  originLabel: "Origine",
  all: "Tutti",
  applyFilters: "Applica filtri",
  blocking: "Bloccanti",
  important: "Importanti",
  ordinary: "Ordinari",
  severity: {
    BLOCKING: "Bloccante",
    IMPORTANT: "Importante",
    ORDINARY: "Ordinario",
  } as Record<string, string>,
  origins: {
    ORDERS: "Ordini",
    DOCUMENTS: "Documenti",
    CUSTOMERS: "Clienti",
    CONNECTIONS: "Collegamenti",
    PRIVACY: "Privacy",
  } as Record<string, string>,
  kinds: {
    TOTALS_MISMATCH: "Totali ordine",
    CUSTOMER_MISMATCH: "Anagrafiche discordanti",
    SOURCE_CONFLICT: "Aggiornamenti ordine",
    ORDER_NOT_BILLABLE: "Ordini non fatturabili",
    HISTORY_RECONCILIATION: "Storico",
    ARUBA_INVOICE_LINK: "Fatture Aruba da collegare",
    ORDER_REVIEW: "Ordini",
    REFUND_REVIEW: "Rimborsi da decidere",
    REFUND_JOB_FAILED: "Rimborsi non elaborati",
    CREDIT_NOTE_APPROVAL: "Note di credito",
    CUSTOMER_IDENTITY: "Identità cliente",
    CONNECTOR_JOB_FAILED: "Sincronizzazioni",
    SHOPIFY_PRIVACY_REQUEST: "Privacy",
    ARUBA_REMOTE_MATCH: "Inventario Aruba",
    ARUBA_OFFICIAL_FILE_REQUIRED: "File Aruba",
    ARUBA_BATCH_RECONCILIATION: "Batch Aruba",
    ARUBA_SUBMISSION_ATTENTION: "Esiti Aruba",
    CUSTOMER_EMAIL_FAILED: "E-mail cliente",
  } as Record<string, string>,
  opened: "Aperto",
  waitingSince: "In attesa",
  evidence: "Evidenze",
  consequence: "Conseguenza",
  openSource: "Apri dettaglio",
  optionalNote: "Nota facoltativa",
  optionalNotePlaceholder: "Aggiungi contesto utile per il registro operativo",
  retry: "Riprova ora",
  confirmPrivacy: "Confermo di avere evaso la richiesta privacy",
  completePrivacy: "Conferma completamento",
  linkAruba: "Collega documento Aruba",
  candidateOrder: "Ordine da collegare",
  confirmOutOfScope: "Conferma fuori perimetro",
  outOfScopeReason: "Documento non riferito a Shopify o eBay",
  officialXml: "XML ufficiale scaricato da Aruba",
  importOfficialXml: "Importa e verifica XML",
  fileAcquired: "File ufficiale acquisito. Il controllo è stato aggiornato.",
  actionCompleted: "Azione completata e risultato verificato.",
  actionWaiting: "Azione avviata. Il controllo resta in attesa dell’esito verificato.",
  emptyOpen: "Nessun controllo da risolvere",
  emptyOpenHelp: "Non risultano decisioni operative aperte.",
  emptyWaiting: "Nessun controllo in attesa",
  emptyWaitingHelp: "Le azioni avviate compariranno qui fino all’esito verificato.",
  noSelection: "Seleziona un controllo per vedere causa, conseguenza e azioni disponibili.",
};
