import { controlKindsCopy, controlOriginsCopy } from "./control-labels.it.ts";

export const controlsCopy = {
  eyebrow: "Lavoro operativo",
  title: "Controlli",
  intro: "Risolvi le decisioni che richiedono il tuo intervento.",
  viewsLabel: "Stato dei controlli",
  open: "Da risolvere",
  waiting: "In attesa",
  severityLabel: "Gravità",
  kindLabel: "Tipo",
  originLabel: "Origine",
  all: "Tutti",
  applyFilters: "Applica filtri",
  searchLabel: "Cerca",
  searchPlaceholder: "Titolo, dettaglio o riferimento",
  results: (count: number) => `${count} ${count === 1 ? "controllo trovato" : "controlli trovati"}`,
  paginationLabel: "Pagine dei controlli",
  previousPage: "Precedenti",
  nextPage: "Successivi",
  blocking: "Bloccanti",
  important: "Importanti",
  ordinary: "Ordinari",
  severity: {
    BLOCKING: "Bloccante",
    IMPORTANT: "Importante",
    ORDINARY: "Ordinario",
  } as Record<string, string>,
  origins: controlOriginsCopy as Record<string, string>,
  kinds: controlKindsCopy as Record<string, string>,
  opened: "Aperto",
  waitingSince: "In attesa",
  evidence: "Evidenze",
  consequence: "Conseguenza",
  openSource: "Apri dettaglio",
  optionalNote: "Nota facoltativa",
  optionalNotePlaceholder: "Aggiungi contesto utile per il registro operativo",
  retry: "Riprova ora",
  confirmPrivacy: "Confermo di avere evaso la richiesta privacy",
  completePrivacy: "Conferma completamento",
  linkAruba: "Collega documento Aruba",
  linkArubaWithDifference: "Collega come fattura già emessa",
  amountMismatchReason: "Motivo della differenza",
  amountMismatchReasonPlaceholder:
    "Descrivi perché il documento Aruba appartiene all’ordine nonostante l’importo diverso",
  confirmAmountMismatchLink:
    "Confermo che il documento Aruba appartiene all’ordine e che la differenza deve restare registrata",
  externalEvidenceReason: "Prova esterna",
  externalEvidenceReasonPlaceholder:
    "Indica chi ha confermato e specifica numero del documento Aruba e ordine collegato",
  confirmExternalEvidenceLink:
    "Confermo che la prova esterna identifica espressamente questo documento Aruba e questo ordine",
  candidateOrder: "Ordine da collegare",
  confirmOutOfScope: "Nessun candidato è corretto",
  confirmCandidateRejection:
    "Confermo di avere confrontato il documento Aruba con tutti i candidati proposti",
  outOfScopeReason: "Documento non riferito a Shopify o eBay",
  officialXml: "XML ufficiale scaricato da Aruba",
  importOfficialXml: "Importa e verifica XML",
  fileAcquired: "File ufficiale acquisito. Il controllo è stato aggiornato.",
  actionCompleted: "Azione completata e risultato verificato.",
  actionWaiting: "Azione avviata. Il controllo resta in attesa dell’esito verificato.",
  waitTitle: "Organizza il seguito",
  waitingReason: "Motivo dell’attesa",
  waitingReasons: {
    PROVIDER: "Risposta del fornitore",
    CUSTOMER: "Risposta del cliente",
    ACCOUNTING: "Verifica contabile",
    TECHNICAL: "Operazione tecnica",
    FOLLOW_UP: "Promemoria operativo",
  } as Record<string, string>,
  dueDate: "Scadenza",
  assignee: "Assegnato a",
  moveToWaiting: "Sposta in attesa",
  reopen: "Riporta da risolvere",
  reopened: "Il controllo è di nuovo nella coda da risolvere.",
  overdue: "Scaduto",
  notAssigned: "Non assegnato",
  emptyOpen: "Nessun controllo da risolvere",
  emptyOpenHelp: "Non risultano decisioni operative aperte.",
  emptyWaiting: "Nessun controllo in attesa",
  emptyWaitingHelp: "Le azioni avviate compariranno qui fino all’esito verificato.",
  noSelection: "Seleziona un controllo per vedere causa, conseguenza e azioni disponibili.",
  backToList: "Torna ai controlli",
};
