import type { AuditAction } from "../src/db/audit.server.ts";
import { errorCatalog, type ErrorCode } from "../src/errors.ts";

const euroFormatter = new Intl.NumberFormat("it-IT", {
  style: "currency",
  currency: "EUR",
});
const integerFormatter = new Intl.NumberFormat("it-IT");

const connectorJobLabels: Record<string, string> = {
  shopify_sync_orders: "Aggiornamento ordini Shopify",
  shopify_process_webhook: "Aggiornamento ricevuto da Shopify",
  ebay_sync_orders: "Aggiornamento ordini eBay",
  ebay_preview_history: "Anteprima ordini eBay",
};

export function errorCodeLabel(code: string | null): string {
  return code && Object.hasOwn(errorCatalog, code)
    ? errorCatalog[code as ErrorCode]
    : "Errore non disponibile";
}

export const copy = {
  appName: "Hub Fatture",
  navigation: {
    dashboard: "Dashboard",
    orders: "Ordini",
    documents: "Documenti",
    activity: "Attività",
    settings: "Impostazioni",
    mainLabel: "Navigazione principale",
    skipToContent: "Vai al contenuto principale",
    openProfile: (username: string) => `Apri il menu di ${username}`,
    ownerRole: "Titolare",
    operatorRole: "Operatore",
    ownerPermission: "Può approvare, numerare e autorizzare gli invii.",
    operatorPermission: "Non può eseguire operazioni fiscali irreversibili.",
    profileSettings: "Profilo e sicurezza",
    logout: "Esci",
  },
  common: {
    unavailable: "Non disponibile",
    unavailablePlural: "Non disponibili",
    unknownStatus: "Stato non riconosciuto",
    unknownType: "Tipo non riconosciuto",
  },
  login: {
    eyebrow: "Area riservata",
    title: "Accedi",
    username: "Nome utente",
    password: "Password",
    submit: "Accedi",
  },
  setup: {
    eyebrow: "Prima configurazione",
    title: "Configura gli accessi",
    code: "Codice di configurazione",
    passwordFor: (username: string) => `Password per ${username} (minimo 8 caratteri)`,
    submit: "Crea gli account",
  },
  dashboard: {
    eyebrow: "Situazione operativa",
    title: "Dashboard",
    summaryLabel: "Riepilogo ordini e fatturazione",
    importedOrders: "Ordini importati",
    readyPreparations: "Preparazioni pronte",
    reviews: "Da verificare",
    waitingOrders: "Ordini non ancora pronti",
    pendingPayments: "Pagamenti in attesa",
    creditNotesToApprove: "Note di credito da approvare",
    failedUploads: "Caricamenti Aruba non riusciti",
    rejectedBySdi: "Documenti scartati da SdI",
    syncErrors: "Errori di sincronizzazione",
    lastShopifySync: "Ultimo aggiornamento Shopify",
    lastEbaySync: "Ultimo aggiornamento eBay",
    lastArubaReadback: "Ultimo readback Aruba",
    documentsToday: "Documenti emessi oggi",
    documentsThisMonth: "Documenti emessi questo mese",
  },
  orders: {
    eyebrow: "Vendite online",
    title: "Ordini",
    intro: "Controlla gli ordini di Shopify ed eBay e prepara le relative fatture.",
    viewsLabel: "Viste ordini",
    views: {
      all: "Tutti",
      toInvoice: "Da fatturare",
      toReview: "Da verificare",
      waiting: "In attesa",
      cancelled: "Annullati",
    },
    filterLabel: "Filtra gli ordini",
    search: "Cerca",
    searchPlaceholder: "Numero ordine o cliente",
    salesChannel: "Canale di vendita",
    orderDate: "Data ordine (facoltativa)",
    payment: "Pagamento",
    invoicingStatus: "Fatturazione",
    filter: "Filtra",
    resultsOnPage: (count: number) =>
      `${count} ${count === 1 ? "risultato" : "risultati"} in questa pagina`,
    activeFilters: (count: number) => `${count} ${count === 1 ? "filtro attivo" : "filtri attivi"}`,
    resetFilters: "Azzera filtri",
    allFeminine: "Tutte",
    allMasculine: "Tutti",
    loadExamples: "Carica ordini di esempio",
    examplesLoaded: (imported: string, updated: string | null, ignored: string | null) =>
      `Ordini di esempio caricati. Nuovi: ${imported}; aggiornati: ${updated ?? "0"}; meno recenti ignorati: ${ignored ?? "0"}.`,
    preparation: "Preparazione fattura",
    customer: "Cliente",
    date: "Data",
    orders: "Ordini",
    total: "Totale",
    status: "Stato",
    order: "Ordine",
    noTransmittedPreparations: "Preparazioni non trasmesse",
    noReviews: "Nessuna verifica richiesta",
    nothingToInvoice: "Niente da fatturare",
    preparationEmptyHelp:
      "Le preparazioni compaiono qui quando gli ordini sono pronti per la fatturazione.",
    cancelledOrders: "Ordini annullati o rimborsati",
    noCancelledOrders: "Nessun ordine annullato",
    noOrders: "Nessun ordine",
    noOrdersHelpDevelopment: "Carica gli ordini di esempio oppure modifica i filtri.",
    noOrdersHelpProduction: "Modifica i filtri oppure attendi la prossima importazione.",
    openPreparation: (number: string) => `Apri preparazione fattura ${number}`,
    massApprovalTitle: "Approvazione in blocco",
    massApprovalSummary: (count: number, total: number) =>
      `${count} documenti standard, totale ${euroFormatter.format(total / 100)}.`,
    massApprovalConfirm:
      "Ho controllato le proiezioni e il percorso Aruba indicato: approva, numera e prepara tutti i documenti elencati.",
    massApprovalConsequence:
      "La numerazione fiscale è irreversibile. Ogni documento usa il profilo salvato nella propria proiezione e la modalità Aruba riepilogata sopra.",
    massApprovalAction: "Approva tutti i documenti standard",
    massApprovalResult: (approved: string, failed: string, storagePending: string) =>
      `Documenti approvati: ${approved}. Non approvati perché cambiati o non più idonei: ${failed}. Archiviazioni da riconciliare: ${storagePending}.`,
  },
  orderDetail: {
    order: (number: string) => `Ordine ${number}`,
    orderStatus: "Stato dell’ordine",
    payment: "Pagamento",
    shipping: "Spedizione",
    invoicing: "Fatturazione",
    preparation: "Preparazione fattura",
    notStarted: "Non avviata",
    prepareNow: "Prepara la fattura ora",
    historyTitle: "Confronta lo storico con Aruba",
    historyHelp:
      "Controlla riferimento ordine, data, cliente e totale. Il solo importo non basta per decidere.",
    historyOutcome: "Esito del confronto",
    alreadyInvoiced: "Documento già presente in Aruba",
    notInvoiced: "Nessun documento corrispondente in Aruba",
    historyReference: "Riferimento verificato o motivazione",
    reconcileHistory: "Registra la riconciliazione",
    historyCompleted: "Storico riconciliato",
    customerData: "Dati del cliente",
    hubCustomerData: "Usati da Hub Fatture",
    customerType: "Tipo cliente",
    email: "E-mail",
    certifiedEmail: "PEC",
    recipientCode: "Codice destinatario SdI",
    address: "Indirizzo",
    shippingAddress: "Indirizzo di spedizione",
    recognizedBy: "Cliente riconosciuto tramite",
    manualCheck: "Controllo manuale",
    required: "Necessario",
    notRequired: "Non necessario",
    taxData: "Dati fiscali",
    receivedCustomerData: (provider: string) => `Ricevuti da ${provider}`,
    name: "Nome",
    receivedTaxData: "Dati fiscali ricevuti",
    possibleMatchTitle: "Possibile cliente già presente",
    possibleMatchHelp:
      "I dati non sono abbastanza certi per unire gli ordini. Se si tratta dello stesso cliente, correggi l’anagrafica della preparazione.",
    taxIdentifier: "Dato fiscale",
    payments: "Pagamenti",
    noPayments: "Nessun pagamento registrato.",
    refunds: "Rimborsi",
    noRefunds: "Nessun rimborso registrato.",
    refundNeedsReview: "Importo da verificare prima di creare la nota di credito.",
    manuallyRecorded: "registrato manualmente",
    purchasedItems: "Articoli acquistati",
    description: "Descrizione",
    quantity: "Quantità",
    amount: "Importo",
    discount: "Sconto",
  },
  preparation: {
    eyebrow: "Da fatturare",
    title: (number: string) => `Preparazione fattura ${number}`,
    includedOrders: "Ordini inclusi",
    summary: "Riepilogo",
    currentStatus: "Situazione",
    currency: "Valuta",
    orders: "Ordini",
    reason: "Motivo della scelta",
    reasonHelp: "Spiega perché questa preparazione non deve diventare una fattura.",
    doNotTransmit: "Non trasmettere",
    reactivate: "Riattiva preparazione",
    reviewWarning: "Prima di proseguire, controlla i dati indicati come incompleti o modificati.",
    notTransmittedDefault: "Questa preparazione non deve essere trasmessa.",
    changesTitle: "Aggiornamenti ricevuti",
    changesIntro: "I dati precedenti restano disponibili nel registro per il controllo.",
    changedOrderData: "I dati ricevuti per questo ordine sono cambiati.",
    checksTitle: "Cose da controllare",
    checkFallback: "Controlla i dati della preparazione prima di proseguire.",
    customerRecord: "Dati cliente",
    customerRecordOriginal: "Ricevuti dal canale di vendita",
    activity: "Registro attività",
    noActivity: "Nessuna attività registrata.",
    archivedOnly: "Questa preparazione resta consultabile in archivio e non può essere riattivata.",
  },
  document: {
    profileMissing: "Il profilo fiscale approvato non è ancora configurato.",
    storagePending:
      "Il documento è approvato e numerato. L’archiviazione XML verrà riconciliata automaticamente prima del download.",
    draftTitle: "Bozza fiscale",
    draftIntro:
      "Una riga semplificata per ordine. Salva prima di approvare per fissare data, importi e descrizioni.",
    approvalDate: (value: string) => `Data documento prevista all’approvazione: ${value}`,
    description: "Descrizione",
    quantity: "Quantità",
    unitAmount: "Importo unitario",
    paymentStatus: "Stato del pagamento",
    paymentMethod: "Modalità di pagamento",
    paymentPaid: "Pagato",
    paymentPending: "In attesa",
    paymentCash: "MP01 · Contanti",
    paymentTransfer: "MP05 · Bonifico",
    paymentCard: "MP08 · Carta",
    causale: "Causale",
    notes: "Note",
    differenceReason: "Motivo della differenza (obbligatorio se il totale cambia)",
    saveDraft: "Salva e valida bozza",
    comparisonTitle: "Confronto fiscale",
    xsdValid: "La proiezione corrente è conforme allo schema FatturaPA 1.2.2.",
    sourceTotal: "Totale ordini",
    documentTotal: "Totale documento",
    difference: "Differenza",
    profile: "Profilo fiscale",
    profileVersion: (version: number) => `versione ${version}`,
    comparisonRecipient: "Destinatario",
    comparisonLines: "Righe",
    comparisonPayment: "Pagamento",
    comparisonNotes: "Causale e note",
    comparisonTechnical: "Dati tecnici e fiscali",
    comparisonField: "Dato",
    comparisonSource: "Origine",
    comparisonDraft: "Bozza",
    comparisonProjection: "Proiezione XML",
    comparisonLine: (line: string) => `Riga ${line}`,
    comparisonLabels: {
      identity: "Identità",
      taxes: "Identificativi fiscali",
      address: "Indirizzo",
      delivery: "Recapito SdI",
      status: "Stato e modalità",
      document: "Documento",
      tax: "Regime e natura",
      causale: "Causale",
      notes: "Note",
      relatedInvoice: "Fattura originaria",
    },
    technicalXml: "Mostra XML tecnico",
    saveBeforeApproval: "Salva la bozza per rendere approvabile questa proiezione.",
    resaveAfterDateChange:
      "La data prevista è cambiata: salva e valida di nuovo la bozza prima dell’approvazione.",
    ownerOnly: "Solo Massimo può approvare e assegnare il numero fiscale.",
    confirmPending: "Confermo che il pagamento è ancora pendente e voglio proseguire.",
    confirmDifference: "Confermo la differenza d’importo motivata nella bozza.",
    finalConfirmation: "Conferma finale",
    confirmDocument: "Documento",
    confirmRecipient: "Destinatario",
    confirmTotal: "Totale",
    confirmProfile: "Profilo fiscale",
    confirmPayment: "Pagamento",
    confirmHelper: "Percorso Aruba",
    customerEmailTitle: "Copia e-mail al cliente",
    emailMode: "Modalità",
    emailAutomatic: "Automatica dopo l’esito SdI",
    emailManual: "Manuale con approvazione",
    emailSender: "Mittente",
    emailRecipient: "Destinatario",
    emailSubject: "Oggetto",
    emailBody: "Corpo",
    emailAttachment: "Allegato",
    emailSend: "Invia dopo il primo esito SdI DELIVERED o NOT_DELIVERED.",
    emailSkip: "Non inviare per questo documento.",
    assistedHelperMode: "Assistita; l’helper si arresta prima di Invia",
    automaticHelperMode:
      "Automatica dopo conferma; il permesso monouso autorizza soltanto questo batch",
    irreversibleNumbering:
      "Con l’approvazione viene assegnato un numero fiscale definitivo che non potrà essere riutilizzato per un altro documento.",
    confirmApproval:
      "Confermo i dati riepilogati e autorizzo l’approvazione e la numerazione irreversibile.",
    approve: "Approva, numera e prepara per Aruba",
  },
  documents: {
    eyebrow: "Archivio fiscale",
    title: "Documenti",
    intro: "Consulta fatture e note di credito, comprese le bozze non ancora approvate.",
    number: "Numero",
    customer: "Cliente",
    date: "Data",
    total: "Totale",
    status: "Stato",
    file: "File",
    approved: "Approvata",
    draft: "Bozza",
    downloadXml: "Scarica XML",
    arubaStatus: "Aruba",
    notPrepared: "Non preparato",
    batchCreated: "Batch Aruba creato con manifest immutabile.",
    fileImported: "File ufficiale importato e verificato.",
    importOfficial: "Importa file ufficiale",
    fileType: "Tipo di file",
    officialFile: "File scaricato da Aruba",
    importAction: "Importa e verifica",
    archivedOfficialFiles: "File ufficiali archiviati",
    emailUncertain: "Esito SMTP incerto: verifica la mancata consegna prima del reinvio.",
    emailUncertainConfirmed: "Ho verificato che il messaggio non è stato consegnato.",
    emailStatus: {
      PENDING: "In attesa",
      SENT: "Inviata",
      FAILED: "Non riuscita",
    } as Record<string, string>,
    officialFileKind: {
      ARUBA_XML: "XML Aruba",
      ARUBA_P7M: "P7M",
      ARUBA_PDF: "PDF Aruba",
      SDI_NOTIFICATION: "Notifica SdI",
    } as Record<string, string>,
    manualBatchTitle: "Prepara documenti già approvati",
    manualBatchHelp:
      "Crea un manifest per i documenti approvati prima dell’attivazione dell’helper.",
    createBatch: "Crea batch Aruba",
    helperCodeTitle: "Codice di avvio helper",
    helperCodeHelp: (expiresAt: string) =>
      `Incollalo nel prompt dell’helper entro ${expiresAt}. Non salvarlo e non inserirlo nella riga di comando.`,
    batchesTitle: "Batch Aruba",
    batchesHelp:
      "Ogni batch resta legato ai documenti, alle revisioni e agli hash approvati. Uno stato incerto richiede readback.",
    batchSummary: (count: number, mode: string) =>
      `${count} ${count === 1 ? "documento" : "documenti"} · ${mode === "AUTOMATIC" ? "Automatica dopo conferma" : "Assistita"}`,
    lastReadback: (value: string) => `ultimo readback ${value}`,
    issueHelperCode: "Genera codice di avvio",
    authorizePermit: "Autorizza nuovo permesso monouso",
    retryBatch: "Prepara nuovo tentativo",
    arubaBatchStatus: {
      PREPARED: "Preparato",
      HELPER_ACTIVE: "Helper attivo",
      VALIDATION_FAILED: "Validazione non riuscita",
      READY_ASSISTED: "Validato; arrestato prima dell’invio",
      PERMIT_CONSUMED: "Permesso consumato",
      SUBMITTED: "Inviato",
      RECONCILIATION_REQUIRED: "Readback necessario",
      RECONCILED: "Riconciliato",
      CANCELLED: "Annullato",
    } as Record<string, string>,
    empty: "Nessun documento",
    emptyHelp: "Le bozze compaiono dopo il primo salvataggio della preparazione.",
    openOrders: "Vai agli ordini",
  },
  activity: {
    eyebrow: "Controlli e cronologia",
    title: "Attività",
    intro: "Vedi subito cosa richiede attenzione e consulta le operazioni già registrate.",
    viewsLabel: "Viste attività",
    toManage: "Da gestire",
    history: "Cronologia",
    nothingToManage: "Niente da gestire",
    nothingToManageHelp:
      "Nessuna preparazione, richiesta privacy o operazione dei canali richiede attenzione.",
    openHistory: "Apri la cronologia",
    openConnections: "Controlla le connessioni",
    dataRequestCompleted: "Richiesta dati Shopify registrata come gestita.",
    jobRetried: "Operazione del canale riavviata.",
    dataRequestsTitle: "Richieste dati Shopify",
    shopifyDataRequest: "Richiesta privacy",
    dataRequestDetail: (customers: number, orders: number) =>
      `${customers} ${customers === 1 ? "cliente" : "clienti"} · ${orders} ${orders === 1 ? "ordine" : "ordini"}`,
    dataRequestComplete: "Segna come gestita",
    failedJobsTitle: "Operazioni non riuscite",
    failedJobTitle: (type: string) => connectorJobLabels[type] ?? "Operazione del canale",
    failedJob: (code: string | null, attempts: number) =>
      `${errorCodeLabel(code)} · ${attempts} ${attempts === 1 ? "tentativo" : "tentativi"}`,
    retryJob: "Riprova ora",
    reviewTitle: "Verifiche su ordini e documenti",
    searchLabel: "Cerca nel registro",
    search: "Cerca",
    searchPlaceholder: "Numero ordine, preparazione o motivo",
    type: "Tipo di attività",
    all: "Tutte",
    filter: "Filtra",
    activity: "Attività",
    subject: "Elemento",
    author: "Autore",
    when: "Quando",
    system: "Sistema",
    recorded: "Attività registrata",
    noHistory: "Nessuna attività registrata",
    noHistoryHelp: "Modifica i filtri oppure attendi la prossima operazione.",
    preparation: (number: string) => `Preparazione fattura ${number}`,
    order: (provider: string, number: string) => `${provider} ${number}`,
    settings: "Impostazioni",
  },
  settings: {
    eyebrow: "Configurazione personale e operativa",
    title: "Impostazioni",
    intro: "Gestisci account, fatturazione, collegamenti e servizi da un’unica pagina.",
    sectionsLabel: "Sezioni delle impostazioni",
    goToSection: "Vai alla sezione",
    profileTitle: "Profilo e sicurezza",
    profileHelp:
      "Rivedi identità, permessi e tema del menu rapido, poi proteggi l’accesso al tuo account.",
    passwordChanged: "Password aggiornata. Le altre sessioni sono state disconnesse.",
    sessionsRevoked: "Le altre sessioni sono state disconnesse.",
    appearanceTitle: "Aspetto",
    passwordTitle: "Password",
    passwordHelp:
      "Usa da 8 a 128 caratteri. Dopo il cambio resterà attiva soltanto questa sessione.",
    currentPassword: "Password attuale",
    newPassword: "Nuova password",
    passwordConfirmation: "Conferma nuova password",
    changePassword: "Aggiorna password",
    sessionsTitle: "Sessioni attive",
    sessionsHelp:
      "Sono mostrate solo le informazioni affidabili disponibili; Hub Fatture non deduce dispositivo o posizione.",
    currentSession: "Questa sessione",
    otherSession: "Altra sessione",
    lastActivity: (value: string) => `Ultima attività: ${value}`,
    sessionExpiry: (value: string) => `Scade: ${value}`,
    revokeOtherSessions: "Disconnetti le altre sessioni",
    noOtherSessions: "Non risultano altre sessioni attive.",
    exitTitle: "Uscita",
    billingTitle: "Fatturazione",
    billingHelp: "Definisci quando un ordine diventa una preparazione fattura.",
    saved: "Impostazione aggiornata. Gli ordini in attesa sono stati ricontrollati.",
    preparationHelp:
      "La modifica vale per gli ordini non ancora inseriti in una preparazione. Quelli già pronti non cambiano.",
    preparationLabel: "Prepara la fattura",
    onPaid: "Quando il pagamento è confermato",
    onFulfilled: "Quando l’ordine è completamente spedito",
    save: "Salva impostazione",
    saveShort: "Salva",
    fiscalTitle: "Profilo fiscale",
    fiscalHelp:
      "Consulta la configurazione fiscale attiva. Le modifiche richiedono un nuovo audit e una nuova versione.",
    fiscalStatus: "Stato",
    fiscalVerified: "Verificato",
    fiscalMock: "Sintetico",
    fiscalVersion: "Versione",
    fiscalRegime: "Regime fiscale",
    fiscalNature: "Natura IVA",
    fiscalSeries: "Serie",
    fiscalCadence: "Numerazione",
    fiscalAnnual: "Annuale",
    fiscalScope: "Ambito contatore",
    fiscalShared: "Condiviso tra fatture e note di credito",
    fiscalLastAudit: "Ultimo audit",
    fiscalMissing: "Il profilo fiscale attivo non è ancora configurato.",
    connectionsTitle: "Connessioni",
    connectionsHelp: "Collega i canali di vendita e controlla gli ultimi aggiornamenti ricevuti.",
    connectionEnvironment: "Ambiente",
    connectionAccount: "Account",
    lastCheck: "Ultimo controllo",
    openActivities: "Apri Attività",
    connect: "Collega",
    reconnect: "Ricollega",
    preview: "Anteprima ultimi 7 giorni",
    connected: "Collegato",
    notConnected: "Non collegato",
    lastSync: "Ultima sincronizzazione",
    never: "Mai",
    previewResult: (provider: string, count: string, review: string) =>
      `${provider}: ${count} ordini nell’anteprima; ${review} con rimborsi da controllare. Nessun ordine è stato importato.`,
    ebayPreviewStatus: (status: string, count: number, review: number, error: string | null) =>
      status === "COMPLETED"
        ? `eBay: ${count} ordini nell’anteprima; ${review} con rimborsi da controllare. Nessun ordine è stato importato.`
        : status === "FAILED"
          ? `L’anteprima eBay non è riuscita (${errorCodeLabel(error)}).`
          : "Anteprima eBay in elaborazione. Ricarica la pagina tra poco.",
    connectionError: (code: string) => `Ultimo errore: ${errorCodeLabel(code)}`,
    customerEmailTitle: "E-mail al cliente",
    customerEmailHelp:
      "Un solo servizio e-mail invia la copia soltanto dopo un esito SdI che conferma l’emissione.",
    customerEmailMode: "Modalità invio copia",
    customerEmailAutomatic: "Automatica dopo l’esito SdI",
    customerEmailManual: "Manuale con approvazione",
    customerEmailSave: "Salva modalità e-mail",
    customerEmailSaved: "Modalità e-mail aggiornata.",
    customerEmailOwnerOnly: "Solo il titolare può cambiare la modalità e-mail.",
    smtpTransport: "Servizio di invio",
    smtpSender: "Mittente",
    smtpStatus: "Configurazione",
    smtpConfigured: "Configurato",
    smtpNotConfigured: "Da completare",
    smtpTransportLabels: {
      SYNTHETIC: "Sintetico, senza rete",
      EXISTING_SMTP: "SMTP esistente",
      OCI_EMAIL_DELIVERY: "OCI Email Delivery",
    } as Record<string, string>,
    arubaTitle: "Integrazione Aruba",
    arubaHelp:
      "L’helper usa Chrome o Edge sul tuo computer. Hub Fatture non conserva credenziali, cookie o codici Aruba.",
    arubaMode: "Modalità Aruba",
    arubaAssisted: "Assistita",
    arubaAutomatic: "Automatica dopo conferma",
    arubaAuthProtection: "Protezione dichiarata",
    arubaAuthUnknown: "Da verificare",
    arubaTwoFactor: "2FA attiva",
    arubaSms: "SMS richiesto a ogni caricamento",
    arubaSaved: "Impostazioni Aruba aggiornate.",
    arubaSave: "Salva integrazione Aruba",
    arubaOwnerOnly: "Solo il titolare può cambiare la modalità Aruba.",
    arubaKillSwitch:
      "Gli invii automatici operativi sono disabilitati: i nuovi batch useranno la modalità assistita.",
    arubaConfiguredMode: "Modalità configurata",
    arubaEffectiveMode: "Modalità effettiva",
    arubaModeLabel: (value: string) =>
      value === "AUTOMATIC" ? "Automatica dopo conferma" : "Assistita",
    helperLastSeen: "Ultimo contatto helper",
    helperVersion: "Versione helper",
    helperBrowser: "Browser helper",
    helperLastReadback: "Ultimo readback",
    systemTitle: "Sistema",
    systemHelp: "Controlla i parametri generali che influenzano tutta l’applicazione.",
    systemOperations: "Operatività",
    systemData: "Dati e backup",
    systemTechnical: "Dettagli tecnici",
    environment: "Ambiente applicativo",
    environmentLabel: (value: string) =>
      value === "production" ? "Produzione" : value === "test" ? "Test" : "Sviluppo",
    timeZone: "Fuso orario",
    applicationVersion: "Versione applicativa",
    commit: "Commit distribuito",
    imageDigest: "Digest immagine",
    databaseSchema: "Schema database",
    workerQueue: "Coda operativa",
    workerQueueStatus: (active: number, failed: number) =>
      `${active} in corso o in attesa; ${failed} non riusciti.`,
    arubaKillSwitchStatus: "Invio automatico Aruba",
    enabled: "Abilitato",
    disabled: "Disabilitato",
    lastBackup: "Ultimo backup verificato",
    backupStatus: (completedAt: string, sizeBytes: number) =>
      `${completedAt} · ${integerFormatter.format(sizeBytes)} byte`,
    backupPending: "Nessuna ricevuta valida disponibile",
    systemOperationalHelp:
      "Questi valori sono riletti dall’applicazione, dal database e dalla ricevuta dell’ultimo backup.",
  },
  customerEditor: {
    title: "Dati del destinatario",
    intro:
      "Le modifiche valgono per questa preparazione. I dati ricevuti dal canale di vendita restano consultabili nel dettaglio dell’ordine.",
    identity: "Cliente",
    address: "Indirizzo di fatturazione",
    tax: "Dati fiscali",
    kind: "Tipo destinatario",
    displayName: "Nome da mostrare",
    firstName: "Nome",
    lastName: "Cognome",
    companyName: "Ragione sociale",
    phone: "Telefono",
    email: "E-mail",
    certifiedEmail: "PEC",
    recipientCode: "Codice destinatario SdI",
    line1: "Indirizzo",
    line2: "Indirizzo, seconda riga",
    postalCode: "CAP",
    city: "Città",
    province: "Provincia",
    country: "Paese",
    countryHelp: "Usa due lettere, per esempio IT per Italia.",
    identifier: (number: number) => `Dato fiscale ${number}`,
    newIdentifier: "Nuovo dato fiscale",
    type: "Tipo",
    value: "Valore",
    emptyRemoves: "Lascia vuoto per rimuoverlo.",
    reason: "Motivo della correzione",
    save: "Salva dati cliente",
  },
  pager: {
    label: "Paginazione",
    previous: "Pagina precedente",
    next: "Pagina successiva",
    current: (page: number) => `Pagina ${page}`,
  },
  theme: {
    label: "Tema",
    system: "Sistema",
    light: "Chiaro",
    dark: "Scuro",
  },
  error: {
    eyebrow: "Errore",
    notFound: "La pagina non esiste",
    unexpected: "La richiesta non è andata a buon fine",
    action: "Torna alla dashboard per continuare.",
    home: "Torna alla dashboard",
  },
} as const;

export const orderStatusLabels: Record<string, string> = {
  WAITING_FOR_TRIGGER: "In attesa di pagamento o spedizione",
  ELIGIBLE: "Da preparare",
  GROUPED: "Fattura in preparazione",
  CANCELLED_NO_DOCUMENT: "Annullato, nessuna fattura",
  REFUNDED_BEFORE_ISSUE: "Rimborsato, nessuna fattura",
  INVOICED: "Fatturato",
  NEEDS_REVIEW: "Da verificare",
  LEGACY_BILLING_REVIEW: "Storico da riconciliare",
};

export const paymentStatusLabels: Record<string, string> = {
  PAID: "Pagato",
  PENDING: "In attesa",
  REFUNDED: "Rimborsato",
};

export const refundStatusLabels: Record<string, string> = {
  PENDING: "In attesa",
  COMPLETED: "Completato",
  FAILED: "Non riuscito",
  AMBIGUOUS: "Da verificare",
};

export const fulfillmentStatusLabels: Record<string, string> = {
  FULFILLED: "Spedito",
  PARTIAL: "Spedito in parte",
  UNFULFILLED: "Non ancora spedito",
};

export const customerKindLabels: Record<string, string> = {
  PRIVATE_IT: "Privato italiano",
  BUSINESS_IT: "Azienda italiana",
  EU: "Cliente UE",
  UNKNOWN: "Tipo da verificare",
};

export const customerMatchLabels: Record<string, string> = {
  TAX_ID: "codice fiscale o partita IVA",
  EXACT_PROFILE: "nome, indirizzo ed e-mail",
  AMBIGUOUS: "dati da verificare",
};

export const taxIdentifierLabels: Record<string, string> = {
  CODICE_FISCALE: "Codice fiscale",
  PARTITA_IVA: "Partita IVA",
  ALTRO: "Altro dato fiscale",
};

export const auditActionLabels = {
  ACCOUNT_PASSWORD_CHANGED: "Password dell’account aggiornata",
  ACCOUNT_SESSIONS_REVOKED: "Altre sessioni disconnesse",
  ADMIN_ACCOUNT_CREATED: "Account amministrativo creato",
  ARUBA_ASSISTED_STOPPED: "Helper arrestato prima dell’invio",
  ARUBA_BATCH_CREATED: "Batch Aruba creato",
  ARUBA_FILE_IMPORTED: "File Aruba importato",
  ARUBA_HELPER_TOKEN_CREATED: "Codice helper generato",
  ARUBA_READBACK_RECONCILED: "Readback Aruba riconciliato",
  ARUBA_RECONCILIATION_REQUIRED: "Riconciliazione Aruba richiesta",
  ARUBA_SEND_PERMIT_CONSUMED: "Permesso Aruba consumato",
  ARUBA_SEND_PERMIT_CREATED: "Permesso Aruba creato",
  ARUBA_SETTINGS_CHANGED: "Impostazioni Aruba modificate",
  ARUBA_UPLOAD_VALIDATED: "Caricamento Aruba validato",
  ARUBA_VALIDATION_FAILED: "Validazione Aruba non riuscita",
  BILLING_CASE_CREATED: "Preparazione fattura creata",
  BILLING_CASE_DO_NOT_TRANSMIT: "Preparazione chiusa senza trasmissione",
  BILLING_CASE_REACTIVATED: "Preparazione riattivata",
  CUSTOMER_CORRECTED: "Anagrafica cliente corretta",
  CUSTOMER_EMAIL_FAILED: "Invio e-mail non riuscito",
  CUSTOMER_EMAIL_QUEUED: "Invio e-mail preparato",
  CUSTOMER_EMAIL_REQUEUED: "Reinvio e-mail preparato",
  CUSTOMER_EMAIL_SENT: "E-mail inviata",
  CUSTOMER_EMAIL_SETTINGS_CHANGED: "Modalità e-mail aggiornata",
  DRAFT_TRIGGER_CHANGED: "Regola di preparazione modificata",
  DOCUMENT_APPROVED: "Documento approvato",
  DOCUMENT_AMOUNT_DIFFERENCE_CONFIRMED: "Differenza d’importo confermata",
  DOCUMENT_DRAFT_SAVED: "Bozza fiscale salvata",
  DOCUMENT_NUMBERED: "Numero fiscale assegnato",
  DOCUMENT_PENDING_PAYMENT_CONFIRMED: "Pagamento pendente confermato",
  FISCAL_PROFILE_ACTIVATED: "Profilo fiscale approvato",
  LOGIN_FAILED: "Accesso rifiutato",
  LOGIN_RATE_LIMITED: "Accessi temporaneamente bloccati",
  LOGIN_SUCCEEDED: "Accesso riuscito",
  LOGOUT_SUCCEEDED: "Uscita registrata",
  ORDER_GROUPED: "Ordine aggiunto alla preparazione",
  ORDER_GROUPING_FORCED: "Preparazione anticipata richiesta",
  ORDER_HISTORY_RECONCILED: "Storico confrontato con Aruba",
  ORDER_IMPORTED: "Ordine importato",
  ORDER_SEPARATED: "Ordine separato dalla preparazione",
  ORDER_SOURCE_CONFLICT: "Aggiornamento dell’ordine da verificare",
  ORDER_SOURCE_UPDATED: "Ordine aggiornato dal canale di vendita",
  PROVIDER_CONNECTED: "Canale di vendita collegato",
  PROVIDER_REVOKED: "Canale di vendita scollegato",
  REFUND_APPLIED_BEFORE_ISSUE: "Rimborso applicato prima dell’emissione",
  REFUND_REVERSED_BEFORE_ISSUE: "Rimborso ripristinato prima dell’emissione",
  REFUND_CREDIT_NOTE_LINKED: "Rimborso collegato alla nota di credito",
  REFUND_CREDIT_NOTE_UPDATED: "Nota di credito aggiornata dal rimborso",
  REFUND_NEEDS_REVIEW: "Rimborso da verificare",
  CONNECTOR_JOB_RETRIED: "Operazione del canale riavviata",
  SHOPIFY_DATA_REQUEST_COMPLETED: "Richiesta dati Shopify gestita",
} satisfies Record<AuditAction, string>;

export function auditActionLabel(action: string) {
  return (auditActionLabels as Record<string, string>)[action];
}

export const billingCaseStatusLabels: Record<string, string> = {
  DRAFT: "In lavorazione",
  NEEDS_REVIEW: "Da verificare",
  READY: "Pronta",
  DO_NOT_TRANSMIT: "Da non trasmettere",
  APPROVED: "Approvata",
  CLOSED: "Chiusa",
};

/** Ogni anomalia dichiara il fatto osservato e l'azione che la chiude (13.9). */
export const anomalyLabels: Record<string, { title: string; action: string }> = {
  PENDING_PAYMENT: {
    title: "Pagamento non ancora acquisito",
    action:
      "Attendi l’incasso oppure registralo nella bozza fiscale senza modificare il canale di vendita.",
  },
  TOTALS_MISMATCH: {
    title: "Totale dell\u2019ordine non riconciliato",
    action:
      "Articoli, spedizione e pagamenti non ricostruiscono il totale ricevuto: verifica l’ordine sul canale di vendita.",
  },
  CUSTOMER_INCOMPLETE: {
    title: "Anagrafica fiscale incompleta",
    action: "Completa i dati del cliente in questa pagina.",
  },
  CUSTOMER_MISMATCH: {
    title: "Anagrafiche discordanti fra gli ordini",
    action: "Correggi l\u2019anagrafica della preparazione oppure separa l\u2019ordine incoerente.",
  },
  SOURCE_CONFLICT: {
    title: "L’ordine è cambiato dopo la preparazione",
    action: "Confronta le versioni conservate qui sotto prima di proseguire.",
  },
  ORDER_NOT_BILLABLE: {
    title: "Ordine annullato o rimborsato",
    action: "Separa l\u2019ordine oppure archivia la preparazione con “Non trasmettere”.",
  },
};

export const reactivationBlockerMessages: Record<string, string> = {
  EMPTY:
    "Questa preparazione storica non contiene più ordini e resta consultabile soltanto in archivio.",
  INCOMPATIBLE_ORDERS:
    "Gli ordini sono ancora annullati o rimborsati. La preparazione resta in archivio finché il canale di vendita non li rettifica.",
  OTHER_OPEN_CASE:
    "Esiste già un’altra preparazione aperta per lo stesso cliente e giorno. Questa resta in archivio.",
};
