export const documentDetailCopy = {
  back: "Torna ai documenti",
  summaryLabel: "Riepilogo del documento",
  draftHelp: "La bozza si rivede e si approva nella preparazione.",
  contentTitle: "Contenuto fiscale",
  contentHelp: "Dati del documento emesso, gli stessi dell’XML trasmesso.",
  contentUnavailable:
    "Il contenuto non è disponibile in forma strutturata: scarica l’XML per consultarlo.",
  recipient: "Cliente",
  taxIdentifiers: "Identificativi fiscali",
  address: "Indirizzo",
  lines: "Righe",
  lineTotal: "Importo",
  payment: "Pagamento",
  taxTreatment: "Trattamento IVA",
  relatedInvoice: "Fattura originaria",
  transmissionTitle: "Trasmissione",
  transmissionHelp: "Stato Aruba e SdI, identificativi e cronologia.",
  noTransmission: "Per questo documento non è registrata una trasmissione.",
  filesTitle: "File",
  emailTitle: "E-mail al cliente",
  linksTitle: "Collegamenti",
  linksHelp: "Ordini, documenti e rimborsi collegati.",
  orders: "Ordini inclusi",
  creditNotes: "Note di credito",
  refunds: "Rimborsi inclusi",
  creditedTotal: "Totale già accreditato",
  remainder: "Residuo accreditabile",
  openPreparation: "Preparazione aperta",
  preparation: (number: string) => `Preparazione fattura ${number}`,
  preparationHelp: "La preparazione richiede ancora una tua decisione.",
  noLinks: "Nessun ordine o documento collegato.",
  emailPrepared: "Nuovo invio e-mail preparato.",
  activityTitle: "Registro attività",
  activityEmpty: "Nessuna attività registrata per questo documento.",
};
