import type { AuditAction } from "../src/db/audit.server.ts";

export const auditActionLabels = {
  ACCOUNT_PASSWORD_CHANGED: "Password dell’account aggiornata",
  ACCOUNT_SESSIONS_REVOKED: "Altre sessioni disconnesse",
  ADMIN_ACCOUNT_CREATED: "Account amministrativo creato",
  ARUBA_ASSISTED_STOPPED: "Percorso storico arrestato prima dell’invio",
  ARUBA_API_AUTHORITY_CHANGED: "Autorità inventario Aruba aggiornata",
  ARUBA_API_BATCH_CONFIRMED: "Trasmissione API Aruba confermata",
  ARUBA_API_CONTROLS_CHANGED: "Controlli API Aruba aggiornati",
  ARUBA_API_CREDENTIALS_CHANGED: "Credenziale API Aruba aggiornata",
  ARUBA_API_DRY_RUN_COMPLETED: "Verifica API Aruba completata",
  ARUBA_API_DRY_RUN_AUTHORIZED: "Verifica API Aruba autorizzata",
  ARUBA_API_DRY_RUN_FAILED: "Verifica API Aruba non riuscita",
  ARUBA_API_DRY_RUN_UNKNOWN: "Verifica API Aruba con esito remoto incerto",
  ARUBA_API_DRY_RUN_STARTED: "Verifica API Aruba avviata",
  ARUBA_API_SEND_STARTED: "Trasmissione Aruba avviata",
  ARUBA_API_SEND_ACCEPTED: "Documento accettato da Aruba",
  ARUBA_API_SEND_FAILED: "Trasmissione Aruba non riuscita",
  ARUBA_API_SEND_UNKNOWN: "Trasmissione Aruba con esito remoto incerto",
  ARUBA_API_READBACK_COMPLETED: "Stato Aruba aggiornato",
  ARUBA_API_READBACK_CONFLICT: "Stato Aruba incompatibile da verificare",
  ARUBA_API_READBACK_REQUESTED: "Aggiornamento stato Aruba richiesto",
  ARUBA_API_SYNC_REQUESTED: "Sincronizzazione API Aruba richiesta",
  ARUBA_BATCH_CREATED: "Batch Aruba creato",
  ARUBA_FILE_IMPORTED: "File Aruba importato",
  ARUBA_READ_SESSION_ISSUED: "Sessione Aruba di sola lettura creata",
  ARUBA_INVENTORY_COMPLETED: "Inventario Aruba completato",
  ARUBA_IDENTITY_CONFLICT_RESOLVED: "Conflitto fra documenti Aruba risolto",
  ARUBA_DOCUMENT_MATCH_RESOLVED: "Documento Aruba collegato manualmente",
  ARUBA_DOCUMENT_CONFIRMED_OUT_OF_SCOPE: "Documento Aruba confermato fuori perimetro",
  ARUBA_PREFLIGHT_OVERRIDDEN: "Controllo Aruba sostituito dopo verifica manuale",
  ARUBA_HELPER_TOKEN_CREATED: "Credenziale temporanea storica generata",
  ARUBA_READBACK_RECONCILED: "Readback Aruba riconciliato",
  ARUBA_RECONCILIATION_REQUIRED: "Riconciliazione Aruba richiesta",
  ARUBA_SEND_AUTHORIZATION_VERIFIED: "Autorizzazione invio Aruba verificata",
  ARUBA_SETTINGS_CHANGED: "Impostazioni Aruba modificate",
  ARUBA_UPLOAD_VALIDATED: "Caricamento Aruba validato",
  ARUBA_VALIDATION_FAILED: "Validazione Aruba non riuscita",
  BILLING_CASE_CREATED: "Preparazione fattura creata",
  BILLING_CASE_DO_NOT_TRANSMIT: "Preparazione chiusa senza trasmissione",
  BILLING_CASE_INVOICED_ORDERS_RECONCILED:
    "Preparazione chiusa perché gli ordini risultano già fatturati",
  BILLING_CASE_ARUBA_IDENTITY_EVIDENCE_RECONCILED:
    "Preparazione riaperta per verificare un documento Aruba plausibile",
  BILLING_CASE_REACTIVATED: "Preparazione riattivata",
  CUSTOMER_CORRECTED: "Anagrafica cliente corretta",
  CUSTOMER_IDENTITY_EXCEPTION_ACCEPTED: "Deroga anagrafica cliente accettata",
  CUSTOMER_IDENTITY_EXCEPTION_APPLIED: "Deroga anagrafica cliente applicata automaticamente",
  CUSTOMER_EMAIL_FAILED: "Invio e-mail non riuscito",
  CUSTOMER_EMAIL_QUEUED: "Invio e-mail preparato",
  CUSTOMER_EMAIL_REQUEUED: "Reinvio e-mail preparato",
  CUSTOMER_EMAIL_SENT: "E-mail inviata",
  CUSTOMER_EMAIL_SETTINGS_CHANGED: "Modalità e-mail aggiornata",
  CUSTOMER_EMAIL_SUPPRESSED: "Invio e-mail soppresso",
  DRAFT_TRIGGER_CHANGED: "Regola di preparazione modificata",
  SHOPIFY_PAYMENT_FEE_MODE_CHANGED: "Regola commissioni Shopify Payments modificata",
  DOCUMENT_APPROVED: "Documento approvato",
  DOCUMENT_AMOUNT_DIFFERENCE_CONFIRMED: "Differenza d’importo confermata",
  DOCUMENT_DRAFT_SAVED: "Bozza fiscale salvata",
  DOCUMENT_NUMBERED: "Numero fiscale assegnato",
  DOCUMENT_PENDING_PAYMENT_CONFIRMED: "Pagamento pendente confermato",
  FISCAL_PROFILE_ACTIVATED: "Profilo fiscale approvato",
  INVOICE_REJECTED_REQUEUED: "Ordine ripristinato dopo lo scarto della fattura",
  LOGIN_FAILED: "Accesso rifiutato",
  LOGIN_RATE_LIMITED: "Accessi temporaneamente bloccati",
  LOGIN_SUCCEEDED: "Accesso riuscito",
  LOGOUT_SUCCEEDED: "Uscita registrata",
  ORDER_GROUPED: "Ordine aggiunto alla preparazione",
  ORDER_GROUPING_FORCED: "Preparazione anticipata richiesta",
  ORDER_HISTORY_RECONCILED: "Storico confrontato con Aruba",
  ORDER_ALREADY_INVOICED_RECONCILED: "Ordine già fatturato rimosso dalla preparazione",
  ORDER_IMPORTED: "Ordine importato",
  ORDER_SEPARATED: "Ordine separato dalla preparazione",
  ORDER_SOURCE_CONFLICT: "Aggiornamento dell’ordine da verificare",
  ORDER_SOURCE_REVIEWED: "Aggiornamento dell’ordine verificato",
  ORDER_SOURCE_UPDATED: "Ordine aggiornato dal canale di vendita",
  PROVIDER_CONNECTED: "Canale di vendita collegato",
  PROVIDER_REVOKED: "Canale di vendita scollegato",
  REFUND_APPLIED_BEFORE_ISSUE: "Rimborso applicato prima dell’emissione",
  REFUND_REVERSED_BEFORE_ISSUE: "Rimborso ripristinato prima dell’emissione",
  RETENTION_APPLIED: "Conservazione tecnica applicata",
  REFUND_CREDIT_NOTE_LINKED: "Rimborso collegato alla nota di credito",
  REFUND_CREDIT_NOTE_UPDATED: "Nota di credito aggiornata dal rimborso",
  REFUND_NEEDS_REVIEW: "Rimborso da verificare",
  CONNECTOR_JOB_RETRIED: "Operazione del canale riavviata",
  SHOPIFY_DATA_REQUEST_COMPLETED: "Richiesta dati Shopify gestita",
} satisfies Record<AuditAction, string>;

export function auditActionLabel(action: string) {
  return (auditActionLabels as Record<string, string>)[action];
}
