import type { AuditAction } from "../src/db/audit.server.ts";
import { errorCatalog, type ErrorCode } from "../src/errors.ts";

const euroFormatter = new Intl.NumberFormat("it-IT", {
  style: "currency",
  currency: "EUR",
});
const integerFormatter = new Intl.NumberFormat("it-IT");

const connectorJobLabels: Record<string, string> = {
  shopify_sync_orders: "Aggiornamento ordini Shopify",
  shopify_process_webhook: "Aggiornamento ricevuto da Shopify",
  ebay_sync_orders: "Aggiornamento ordini eBay",
  ebay_preview_history: "Storico ordini eBay",
};

export function errorCodeLabel(code: string | null): string {
  return code && Object.hasOwn(errorCatalog, code)
    ? errorCatalog[code as ErrorCode]
    : "Errore non disponibile";
}

export const copy = {
  table: {
    sortControls: "Ordina la tabella",
    sortLabel: (label: string, direction: "asc" | "desc" | null) =>
      direction === "asc"
        ? `${label}: ordine crescente. Attiva per ordinare in senso decrescente`
        : direction === "desc"
          ? `${label}: ordine decrescente. Attiva per ordinare in senso crescente`
          : `${label}: attiva per ordinare in senso crescente`,
  },
  appName: "Hub Fatture",
  navigation: {
    dashboard: "Dashboard",
    orders: "Ordini",
    documents: "Documenti",
    customers: "Clienti",
    activity: "Attività",
    settings: "Impostazioni",
    collapseSidebar: "Comprimi navigazione",
    expandSidebar: "Espandi navigazione",
    more: "Altro",
    openMore: "Apri altre sezioni",
    mainLabel: "Navigazione principale",
    skipToContent: "Vai al contenuto principale",
    openProfile: (username: string) => `Apri il menu di ${username}`,
    ownerRole: "Titolare",
    operatorRole: "Operatore",
    ownerPermission: "Può approvare, numerare e autorizzare gli invii.",
    operatorPermission: "Non può eseguire operazioni fiscali irreversibili.",
    profileSettings: "Profilo e sicurezza",
    logout: "Esci",
  },
  search: {
    open: "Apri la ricerca globale",
    trigger: "Cerca in Hub Fatture",
    title: "Ricerca globale",
    label: "Cerca ordini, fatture e clienti",
    placeholder: "Ordine, fattura, cliente, e-mail o dato fiscale",
    clear: "Cancella la ricerca",
    startTitle: "Trova subito ciò che ti serve",
    startHelp: "Cerca per numero, nome, e-mail, codice fiscale o partita IVA.",
    loading: "Ricerca in corso…",
    errorTitle: "Ricerca momentaneamente non disponibile",
    errorHelp: "Riprova fra qualche istante.",
    emptyTitle: "Nessun risultato",
    emptyHelp: (query: string) =>
      `Nessuna corrispondenza per “${query}”. Controlla il testo e riprova.`,
    results: (count: number) =>
      `${count} ${count === 1 ? "risultato trovato" : "risultati trovati"}`,
    orders: "Ordini",
    invoices: "Fatture",
    customers: "Clienti",
    order: (provider: string, number: string) =>
      `Ordine ${provider === "SHOPIFY" ? "Shopify" : "eBay"} ${number}`,
    invoice: (number: string) => `Fattura ${number}`,
    invoicePreparation: (number: string) => `Preparazione fattura ${number}`,
    issued: "Emessa",
    draft: "In preparazione",
    noContact: "Recapito non disponibile",
    customerOrders: (count: number) => `${count} ${count === 1 ? "ordine" : "ordini"}`,
    keyboardHelp: "Usa Tab per muoverti fra i risultati",
  },
  customer: {
    eyebrow: "Cliente",
    intro: (orders: number, documents: number) =>
      `${orders} ${orders === 1 ? "ordine" : "ordini"} · ${documents} ${documents === 1 ? "fattura" : "fatture"}`,
    data: "Dati cliente",
    email: "E-mail",
    phone: "Telefono",
    taxCode: "Codice fiscale",
    vatNumber: "Partita IVA",
    billingAddress: "Indirizzo di fatturazione",
    orders: "Ordini",
    invoices: "Fatture",
    orderCount: (count: number) =>
      `${count} ${count === 1 ? "ordine collegato" : "ordini collegati"}`,
    documentCount: (count: number) =>
      `${count} ${count === 1 ? "fattura collegata" : "fatture collegate"}`,
    noOrders: "Nessun ordine collegato a questo cliente.",
    noInvoices: "Nessuna fattura collegata a questo cliente.",
    allOrders: "Vedi tutti gli ordini",
    kinds: {
      PRIVATE_IT: "Privato italiano",
      BUSINESS_IT: "Azienda o professionista italiano",
      EU: "Cliente dell’Unione europea",
      UNKNOWN: "Tipologia da verificare",
    } as Record<string, string>,
    documentStatuses: {
      DRAFT: "In preparazione",
      APPROVED: "Emessa",
    } as Record<string, string>,
  },
  common: {
    unavailable: "Non disponibile",
    unavailablePlural: "Non disponibili",
    unknownStatus: "Stato non riconosciuto",
    unknownType: "Tipo non riconosciuto",
  },
  publicPage: {
    intro: "Ordini, documenti fiscali e attività operative in un unico spazio riservato.",
  },
  login: {
    eyebrow: "Area riservata",
    title: "Accedi",
    intro: "Inserisci le credenziali del tuo account per continuare.",
    username: "Nome utente",
    password: "Password",
    submit: "Accedi",
  },
  setup: {
    eyebrow: "Prima configurazione",
    title: "Configura gli accessi",
    intro: "Crea i due account operativi. Ruoli e autorizzazioni resteranno separati.",
    code: "Codice di configurazione",
    codeHelp: "Usa il codice temporaneo ricevuto per inizializzare l’applicazione.",
    ownerTitle: "Account titolare",
    ownerHelp: "Può approvare, numerare e autorizzare gli invii.",
    operatorTitle: "Account operatore",
    operatorHelp: "Può preparare e verificare i dati, senza approvare documenti fiscali.",
    passwordFor: (username: string) => `Password per ${username} (minimo 8 caratteri)`,
    submit: "Crea gli account",
  },
  dashboard: {
    eyebrow: "Situazione operativa",
    title: "Dashboard",
    summaryLabel: "Riepilogo ordini e fatturazione",
    workNow: "Da fare ora",
    readyDetail: "Pronte per l’approvazione",
    reviewDetail: "Richiede attenzione",
    pendingDetail: "In attesa di gestione",
    creditNoteDetail: "Pronte per l’approvazione",
    openPreparations: "Apri preparazioni",
    openOrders: "Apri ordini",
    openActivity: "Apri attività",
    operationalStatus: "Stato operativo",
    allUnderControl: "Tutto sotto controllo",
    noCurrentIssues: "Nessuna criticità al momento",
    updatesMissing: "Aggiornamenti da completare",
    updatesMissingDetail: "Uno o più collegamenti non hanno ancora restituito dati",
    attentionNeeded: "Richiede attenzione",
    attentionNeededDetail: "Sono presenti criticità operative da gestire",
    noFailedUploads: "Nessun caricamento Aruba non riuscito",
    noRejectedDocuments: "Nessun documento scartato da SdI",
    noSyncErrors: "Nessun errore di sincronizzazione",
    failedUploadsCount: (count: number) =>
      `${count} ${count === 1 ? "caricamento Aruba non riuscito" : "caricamenti Aruba non riusciti"}`,
    rejectedDocumentsCount: (count: number) =>
      `${count} ${count === 1 ? "documento scartato da SdI" : "documenti scartati da SdI"}`,
    syncErrorsCount: (count: number) =>
      `${count} ${count === 1 ? "errore di sincronizzazione" : "errori di sincronizzazione"}`,
    connections: "Collegamenti",
    updated: "Aggiornato",
    stale: "Da aggiornare",
    neverUpdated: "Mai aggiornato",
    neverRead: "Mai letto",
    documents: "Documenti",
    issuedToday: "emessi oggi",
    issuedThisMonth: "questo mese",
    lastSevenDays: "Ultimi 7 giorni",
    documentsInDay: (count: number, date: string) =>
      `${count} ${count === 1 ? "documento emesso" : "documenti emessi"} ${date}`,
    importedOrders: "Ordini importati",
    readyPreparations: "Preparazioni pronte",
    reviews: "Da verificare",
    waitingOrders: "Ordini non ancora pronti",
    pendingPayments: "Pagamenti in attesa",
    creditNotesToApprove: "Note di credito da approvare",
    failedUploads: "Caricamenti Aruba non riusciti",
    rejectedBySdi: "Documenti scartati da SdI",
    syncErrors: "Errori di sincronizzazione",
    lastShopifySync: "Ultimo aggiornamento Shopify",
    lastEbaySync: "Ultimo aggiornamento eBay",
    lastArubaReadback: "Ultimo readback Aruba",
    documentsToday: "Documenti emessi oggi",
    documentsThisMonth: "Documenti emessi questo mese",
  },
  orders: {
    eyebrow: "Vendite online",
    title: "Ordini",
    intro: "Controlla gli ordini di Shopify ed eBay e prepara le relative fatture.",
    viewsLabel: "Viste ordini",
    views: {
      all: "Tutti",
      toInvoice: "Da fatturare",
      toReview: "Da verificare",
      waiting: "In attesa",
      cancelled: "Annullati",
    },
    filterLabel: "Filtra gli ordini",
    filterTitle: "Trova gli ordini",
    filterHelp: "Combina i criteri senza perdere la vista corrente.",
    search: "Cerca",
    searchPlaceholder: "Numero ordine o cliente",
    salesChannel: "Canale di vendita",
    orderDate: "Data ordine (facoltativa)",
    payment: "Pagamento",
    invoicingStatus: "Fatturazione",
    filter: "Filtra",
    resultsOnPage: (count: number) =>
      `${count} ${count === 1 ? "risultato" : "risultati"} in questa pagina`,
    activeFilters: (count: number) => `${count} ${count === 1 ? "filtro attivo" : "filtri attivi"}`,
    resetFilters: "Azzera filtri",
    allFeminine: "Tutte",
    allMasculine: "Tutti",
    loadExamples: "Carica ordini di esempio",
    examplesLoaded: (imported: string, updated: string | null, ignored: string | null) =>
      `Ordini di esempio caricati. Nuovi: ${imported}; aggiornati: ${updated ?? "0"}; meno recenti ignorati: ${ignored ?? "0"}.`,
    preparation: "Preparazione fattura",
    preparationContext: "Preparazione",
    preparationListTitle: "Preparazioni fattura",
    preparationListHelp:
      "Apri una preparazione per controllare dati, anomalie e passaggi successivi.",
    customer: "Cliente",
    date: "Data",
    orders: "Ordini",
    total: "Totale",
    status: "Stato",
    order: "Ordine",
    orderListTitle: "Elenco ordini",
    orderListHelp: "Gli ordini più recenti, con stato e destinazione sempre riconoscibili.",
    channel: "Canale",
    actions: "Azioni",
    noPreparation: "Non ancora creata",
    openOrder: (provider: string, number: string) => `Apri dettaglio ordine ${provider} ${number}`,
    openOrderAction: "Apri dettaglio",
    openPreparationAction: "Apri preparazione",
    openPreparationDetail: (number: string) => `Apri dettaglio preparazione fattura ${number}`,
    pageItems: (count: number) => `${count} ${count === 1 ? "elemento" : "elementi"}`,
    noTransmittedPreparations: "Preparazioni non trasmesse",
    historicalOrders: "Ordini storici da riconciliare",
    noReviews: "Nessuna verifica richiesta",
    nothingToInvoice: "Niente da fatturare",
    preparationEmptyHelp:
      "Le preparazioni compaiono qui quando gli ordini sono pronti per la fatturazione.",
    cancelledOrders: "Ordini annullati o rimborsati",
    noCancelledOrders: "Nessun ordine annullato",
    noOrders: "Nessun ordine",
    noOrdersHelpDevelopment: "Carica gli ordini di esempio oppure modifica i filtri.",
    noOrdersHelpProduction: "Modifica i filtri oppure attendi la prossima importazione.",
    openPreparation: (number: string) => `Apri preparazione fattura ${number}`,
    massApprovalTitle: "Approvazione in blocco",
    massApprovalSummary: (count: number, total: number) =>
      `${count} documenti standard, totale ${euroFormatter.format(total / 100)}.`,
    massApprovalConfirm:
      "Ho controllato le proiezioni e il percorso Aruba indicato: approva, numera e prepara tutti i documenti elencati.",
    massApprovalConsequence:
      "La numerazione fiscale è irreversibile. Ogni documento usa il profilo salvato nella propria proiezione e la modalità Aruba riepilogata sopra.",
    massApprovalAction: "Approva tutti i documenti standard",
    massApprovalResult: (approved: string, failed: string, storagePending: string) =>
      `Documenti approvati: ${approved}. Non approvati perché cambiati o non più idonei: ${failed}. Archiviazioni da riconciliare: ${storagePending}.`,
  },
  customers: {
    eyebrow: "Anagrafiche correnti",
    title: "Clienti",
    intro:
      "Consulta i dati cliente riconciliati da Shopify ed eBay e raggiungi ordini, preparazioni e documenti collegati.",
    overviewLabel: "Riepilogo clienti",
    totalCount: (count: number) =>
      `${count} ${count === 1 ? "cliente importato" : "clienti importati"}`,
    overviewHelp: "Le anagrafiche vengono aggiornate quando arrivano nuovi dati dai canali.",
    needsReviewCount: "Da verificare",
    shopifyCount: "Da Shopify",
    ebayCount: "Da eBay",
    viewsLabel: "Viste clienti",
    views: {
      all: "Tutti",
      needsReview: "Da verificare",
    },
    filterLabel: "Cerca clienti",
    search: "Cerca",
    searchPlaceholder: "Nome, e-mail, codice fiscale o partita IVA",
    filter: "Cerca",
    resultsOnPage: (count: number) =>
      `${count} ${count === 1 ? "risultato" : "risultati"} in questa pagina`,
    activeFilter: "Ricerca attiva",
    resetFilters: "Azzera ricerca",
    directoryTitle: "Elenco clienti",
    directoryHelp: "Apri un cliente per vedere tutti i collegamenti disponibili.",
    customer: "Cliente",
    email: "E-mail",
    taxIdentifier: "Identificativo fiscale",
    taxData: "Dato fiscale",
    channels: "Canali",
    lastOrder: "Ultimo ordine",
    orders: "Ordini",
    documents: "Documenti",
    actions: "Azioni",
    activity: "Attività",
    orderCount: (count: number) => `${count} ${count === 1 ? "ordine" : "ordini"}`,
    documentCount: (count: number) => `${count} ${count === 1 ? "documento" : "documenti"}`,
    openCustomer: (name: string) => `Apri cliente ${name}`,
    openDetail: "Apri dettaglio",
    needsReview: "Dati da verificare",
    reliable: "Dati riconciliati",
    noCustomers: "Nessun cliente",
    noCustomersHelp: "I clienti compaiono dopo l’importazione del primo ordine.",
    noResults: "Nessun cliente corrisponde alla ricerca",
    noResultsHelp: "Prova con un nome, un’e-mail o un identificativo fiscale diverso.",
    backToCustomers: "Torna ai clienti",
    currentRecord: "Anagrafica corrente",
    currentRecordHelp:
      "Le correzioni fatte durante una preparazione valgono per quel documento e non riscrivono gli ordini già importati.",
    customerType: "Tipo cliente",
    name: "Nome",
    phone: "Telefono",
    address: "Indirizzo di fatturazione",
    recognizedBy: "Riconosciuto tramite",
    created: "Prima importazione",
    updated: "Ultimo aggiornamento",
    sourceTitle: "Origine dei dati",
    sourceHelp: "Riferimenti con cui i canali identificano questa anagrafica.",
    sourceReference: "Riferimento canale",
    sourceUpdated: "Aggiornato",
    statusLabel: "Stato dell’anagrafica",
    reviewHelp: "Controlla l’ordine o la preparazione collegata prima di approvare un documento.",
    ordersTitle: "Ordini collegati",
    preparationsTitle: "Preparazioni fattura",
    documentsTitle: "Documenti",
    linkedItemsHelp: "Sono mostrati prima gli elementi più recenti.",
    preparation: "Preparazione fattura",
    date: "Data",
    total: "Totale",
    status: "Stato",
    document: "Documento",
    draftInvoice: "Bozza fattura",
    draftCreditNote: "Bozza nota di credito",
    invoice: "Fattura",
    creditNote: "Nota di credito",
    latestLimit: "Sono mostrati gli ultimi 50 elementi.",
    noSources: "Nessun riferimento di canale disponibile.",
    noOrders: "Nessun ordine collegato.",
    noPreparations: "Nessuna preparazione collegata.",
    noDocuments: "Nessun documento collegato.",
  },
  orderDetail: {
    order: (number: string) => `Ordine ${number}`,
    orderStatus: "Stato dell’ordine",
    orderStatusHelp: "Pagamento, spedizione e importi utili alla fatturazione.",
    payment: "Pagamento",
    shipping: "Spedizione",
    invoicing: "Fatturazione",
    preparation: "Preparazione fattura",
    orderTotal: "Totale ordine",
    shopifyPaymentsFee: "Commissione Shopify Payments sottratta",
    billableTotal: "Totale fatturabile",
    notStarted: "Non avviata",
    prepareNow: "Prepara la fattura ora",
    historyTitle: "Confronta lo storico con Aruba",
    historyHelp:
      "Controlla riferimento ordine, data, cliente e totale. Il solo importo non basta per decidere.",
    historyOutcome: "Esito del confronto",
    alreadyInvoiced: "Documento già presente in Aruba",
    notInvoiced: "Nessun documento corrispondente in Aruba",
    historyReference: "Riferimento verificato o motivazione",
    historyInvoiceXml: "XML ufficiale della fattura Aruba, se già presente",
    manualReviewApproved:
      "Autorizzo l’eccezione manuale dopo aver verificato identità, indirizzo, data, totale e unicità del documento.",
    reconcileHistory: "Registra la riconciliazione",
    historyCompleted: "Storico riconciliato",
    customerData: "Dati del cliente",
    customerDataHelp: "Confronta l’anagrafica in uso con i dati ricevuti dal canale.",
    hubCustomerData: "Usati da Hub Fatture",
    customerType: "Tipo cliente",
    email: "E-mail",
    certifiedEmail: "PEC",
    recipientCode: "Codice destinatario SdI",
    address: "Indirizzo",
    shippingAddress: "Indirizzo di spedizione",
    recognizedBy: "Cliente riconosciuto tramite",
    manualCheck: "Controllo manuale",
    required: "Necessario",
    notRequired: "Non necessario",
    taxData: "Dati fiscali",
    receivedCustomerData: (provider: string) => `Ricevuti da ${provider}`,
    name: "Nome",
    receivedTaxData: "Dati fiscali ricevuti",
    possibleMatchTitle: "Possibile cliente già presente",
    possibleMatchHelp:
      "I dati non sono abbastanza certi per unire gli ordini. Se si tratta dello stesso cliente, correggi l’anagrafica della preparazione.",
    taxIdentifier: "Dato fiscale",
    payments: "Pagamenti",
    noPayments: "Nessun pagamento registrato.",
    refunds: "Rimborsi",
    noRefunds: "Nessun rimborso registrato.",
    refundNeedsReview: "Importo da verificare prima di creare la nota di credito.",
    manuallyRecorded: "registrato manualmente",
    purchasedItems: "Articoli acquistati",
    purchasedItemsHelp: "Righe economiche ricevute per questo ordine.",
    description: "Descrizione",
    quantity: "Quantità",
    amount: "Importo",
    discount: "Sconto",
  },
  creditNote: {
    eyebrow: "Nota di credito",
    title: "Bozza TD04",
    sourceInvoice: (number: string, invoiceDate: string) =>
      `Fattura originaria ${number} del ${invoiceDate}`,
    balanceTitle: "Residuo accreditabile",
    balanceHelp: "Importi aggiornati includendo la bozza corrente.",
    invoiceTotal: "Totale fattura",
    creditedTotal: "Totale note",
    remainingAfterDraft: "Residuo dopo questa bozza",
    draftTotal: "Totale bozza",
    comparisonTitle: "Comparatore fiscale",
    comparisonHelp: "Confronta origine, bozza e proiezione XML prima dell’approvazione.",
    sourceInvoiceComparison: "Fattura originaria",
    approvalTitle: "Approvazione e invio",
    approvalHelp: "Controlla la copia e-mail e conferma soltanto dopo la verifica fiscale.",
    confirmation:
      "Confermo rimborsi, riferimenti alla fattura, totale e numerazione irreversibile.",
    approve: "Approva, numera e prepara per Aruba",
    back: "Torna ai documenti",
  },
  preparation: {
    eyebrow: "Da fatturare",
    title: (number: string) => `Preparazione fattura ${number}`,
    includedOrders: "Ordini inclusi",
    summary: "Riepilogo",
    currentStatus: "Situazione",
    currency: "Valuta",
    orders: "Ordini",
    reason: "Motivo della scelta",
    reasonHelp: "Spiega perché questa preparazione non deve diventare una fattura.",
    doNotTransmit: "Non trasmettere",
    reactivate: "Riattiva preparazione",
    reviewWarning: "Prima di proseguire, controlla i dati indicati come incompleti o modificati.",
    notTransmittedDefault: "Questa preparazione non deve essere trasmessa.",
    changesTitle: "Aggiornamenti ricevuti",
    changesIntro: "I dati precedenti restano disponibili nel registro per il controllo.",
    changedOrderData: "I dati ricevuti per questo ordine sono cambiati.",
    sourceChangesField: "Dato",
    sourceChangesBefore: "Prima",
    sourceChangesNow: "Adesso",
    sourceChangesEmpty: "Nessuna differenza operativa leggibile.",
    sourceReviewConfirmation:
      "Confermo di avere confrontato gli aggiornamenti ricevuti con la preparazione corrente.",
    sourceReviewHelp:
      "La conferma chiude soltanto questo controllo. Eventuali anomalie su cliente, importi o pagamento restano bloccanti.",
    sourceReviewSubmit: "Segna gli aggiornamenti come verificati",
    sourceChangeFields: {
      displayNumber: "Numero ordine",
      localOrderDate: "Data ordine",
      billableAmount: "Totale fatturabile",
      payment: "Pagamento",
      fulfillment: "Evasione",
      cancellation: "Annullamento",
      customerName: "Cliente",
      firstName: "Nome",
      lastName: "Cognome",
      customerKind: "Tipo destinatario",
      companyName: "Ragione sociale",
      email: "E-mail",
      certifiedEmail: "PEC",
      recipientCode: "Codice destinatario SdI",
      phone: "Telefono",
      billingAddress: "Indirizzo di fatturazione",
      shippingAddress: "Indirizzo di spedizione",
      taxIdentifiers: "Identificativi fiscali",
      totalAmount: "Totale ordine",
      shippingAmount: "Spese di spedizione",
      lines: "Articoli",
      refunds: "Rimborsi",
      sourceReviewRequired: "Segnalazione del canale",
    } as Record<string, string>,
    sourceReviewRequested: "Da controllare",
    sourceReviewNotRequested: "Nessun controllo richiesto",
    checksTitle: "Cose da controllare",
    checkFallback: "Controlla i dati della preparazione prima di proseguire.",
    customerRecord: "Dati cliente",
    customerRecordOriginal: "Ricevuti dal canale di vendita",
    activity: "Registro attività",
    noActivity: "Nessuna attività registrata.",
    archivedOnly: "Questa preparazione resta consultabile in archivio e non può essere riattivata.",
  },
  document: {
    profileMissing: "Il profilo fiscale approvato non è ancora configurato.",
    storagePending:
      "Il documento è approvato e numerato. L’archiviazione XML verrà riconciliata automaticamente prima del download.",
    draftTitle: "Bozza fiscale",
    draftIntro:
      "Una riga semplificata per ordine. Salva prima di approvare per fissare data, importi e descrizioni.",
    approvalDate: (value: string) => `Data documento prevista all’approvazione: ${value}`,
    description: "Descrizione",
    quantity: "Quantità",
    unitAmount: "Importo unitario",
    paymentStatus: "Stato del pagamento",
    paymentMethod: "Modalità di pagamento",
    paymentPaid: "Pagato",
    paymentPending: "In attesa",
    paymentCash: "MP01 · Contanti",
    paymentTransfer: "MP05 · Bonifico",
    paymentCard: "MP08 · Carta",
    causale: "Causale",
    notes: "Note",
    differenceReason: "Motivo della differenza (obbligatorio se il totale cambia)",
    saveDraft: "Salva e valida bozza",
    comparisonTitle: "Confronto fiscale",
    xsdValid: "La proiezione corrente è conforme allo schema FatturaPA 1.2.2.",
    grossTotal: "Totale ordini",
    shopifyPaymentsFeeTotal: "Commissioni Shopify Payments sottratte",
    sourceTotal: "Totale fatturabile",
    documentTotal: "Totale documento",
    difference: "Differenza",
    profile: "Profilo fiscale",
    profileVersion: (version: number) => `versione ${version}`,
    comparisonRecipient: "Destinatario",
    comparisonLines: "Righe",
    comparisonPayment: "Pagamento",
    comparisonNotes: "Causale e note",
    comparisonTechnical: "Dati tecnici e fiscali",
    comparisonField: "Dato",
    comparisonSource: "Origine",
    comparisonDraft: "Bozza",
    comparisonProjection: "Proiezione XML",
    comparisonLine: (line: string) => `Riga ${line}`,
    comparisonLabels: {
      identity: "Identità",
      taxes: "Identificativi fiscali",
      address: "Indirizzo",
      delivery: "Recapito SdI",
      status: "Stato e modalità",
      document: "Documento",
      tax: "Regime e natura",
      causale: "Causale",
      notes: "Note",
      relatedInvoice: "Fattura originaria",
    },
    technicalXml: "Mostra XML tecnico",
    saveBeforeApproval: "Salva la bozza per rendere approvabile questa proiezione.",
    resaveAfterDateChange:
      "La data prevista è cambiata: salva e valida di nuovo la bozza prima dell’approvazione.",
    ownerOnly: "Solo Massimo può approvare e assegnare il numero fiscale.",
    confirmPending: "Confermo che il pagamento è ancora pendente e voglio proseguire.",
    confirmDifference: "Confermo la differenza d’importo motivata nella bozza.",
    finalConfirmation: "Conferma finale",
    confirmDocument: "Documento",
    confirmRecipient: "Destinatario",
    confirmTotal: "Totale",
    confirmProfile: "Profilo fiscale",
    confirmPayment: "Pagamento",
    confirmHelper: "Percorso Aruba",
    customerEmailTitle: "Copia e-mail al cliente",
    emailMode: "Modalità",
    emailAutomatic: "Automatica dopo l’esito SdI",
    emailManual: "Manuale con approvazione",
    emailSender: "Mittente",
    emailRecipient: "Destinatario",
    emailSubject: "Oggetto",
    emailBody: "Corpo",
    emailAttachment: "Allegato",
    emailSend: "Invia dopo il primo esito SdI DELIVERED o NOT_DELIVERED.",
    emailSkip: "Non inviare per questo documento.",
    assistedHelperMode: "Assistita; l’helper si arresta prima di Invia",
    automaticHelperMode:
      "Automatica dopo conferma; il permesso monouso autorizza soltanto questo batch",
    irreversibleNumbering:
      "Con l’approvazione viene assegnato un numero fiscale definitivo che non potrà essere riutilizzato per un altro documento.",
    confirmApproval:
      "Confermo i dati riepilogati e autorizzo l’approvazione e la numerazione irreversibile.",
    approve: "Approva, numera e prepara per Aruba",
  },
  documents: {
    eyebrow: "Archivio fiscale",
    title: "Documenti",
    intro:
      "Trova fatture e note di credito, controlla gli esiti e apri subito il documento giusto.",
    viewsLabel: "Viste documenti",
    all: "Tutti",
    invoices: "Fatture",
    creditNotes: "Note di credito",
    toSend: "Da trasmettere",
    toReconcile: "Da riconciliare",
    overviewLabel: "Riepilogo documenti",
    overviewCount: (count: number) =>
      `${count} ${count === 1 ? "documento in archivio" : "documenti in archivio"}`,
    overviewHelp: "Fatture, note di credito e bozze sono raccolte in un unico archivio.",
    overviewInvoices: "Fatture",
    overviewCreditNotes: "Note di credito",
    overviewToSend: "Da trasmettere",
    overviewToReconcile: "Readback richiesto",
    archiveTitle: "Archivio documenti",
    archiveHelp:
      "Filtra l’elenco senza perdere di vista stato, cliente, importo e prossima azione.",
    archiveCount: (count: number) =>
      `${count} ${count === 1 ? "documento in questa pagina" : "documenti in questa pagina"}`,
    filterLabel: "Filtra i documenti",
    search: "Cerca",
    searchPlaceholder: "Numero o cliente",
    type: "Tipo",
    approvalStatus: "Stato documento",
    transmissionStatus: "Stato trasmissione",
    dateFrom: "Dal",
    dateTo: "Al",
    filter: "Filtra",
    resetFilters: "Azzera filtri",
    resultsOnPage: (count: number) =>
      `${count} ${count === 1 ? "risultato nella pagina" : "risultati nella pagina"}`,
    activeFilters: (count: number) => `${count} ${count === 1 ? "filtro attivo" : "filtri attivi"}`,
    document: "Documento",
    number: "Numero",
    customer: "Cliente",
    date: "Data",
    dateAndTotal: "Data e totale",
    total: "Totale",
    status: "Stato",
    file: "File",
    actions: "Azioni",
    approved: "Approvato",
    draft: "Bozza",
    draftLabel: (number: string) => `Bozza ${number}`,
    invoice: "Fattura",
    creditNote: "Nota di credito",
    openDocument: "Apri documento",
    openDocumentLabel: (label: string) => `Apri ${label}`,
    downloadXml: "Scarica XML",
    arubaStatus: "Aruba",
    notPrepared: "Non preparato",
    arubaHistory: "Storico Aruba",
    notApplicable: "Dopo l’approvazione",
    transmissionState: {
      NOT_PREPARED: "Da preparare per Aruba",
      PREPARED: "Preparato per Aruba",
      HELPER_ACTIVE: "Helper attivo",
      VALIDATION_FAILED: "Validazione non riuscita",
      READY_ASSISTED: "Pronto per l’invio manuale",
      PERMIT_CONSUMED: "Permesso consumato",
      SUBMITTED: "Inviato, esito da verificare",
      RECONCILIATION_REQUIRED: "Readback necessario",
      RECONCILED: "Riconciliato",
      CANCELLED: "Tentativo annullato",
    } as Record<string, string>,
    allTypes: "Tutti",
    allStatuses: "Tutti",
    allTransmissionStatuses: "Tutti",
    filesAndActions: "File e azioni",
    availableFiles: (count: number) =>
      `${count} ${count === 1 ? "file disponibile" : "file disponibili"}`,
    noOfficialFiles: "Nessun file ufficiale importato.",
    batchCreated: "Batch Aruba creato con manifest immutabile.",
    fileImported: "File ufficiale importato e verificato.",
    importOfficial: "Importa file ufficiale",
    fileType: "Tipo di file",
    officialFile: "File scaricato da Aruba",
    importAction: "Importa e verifica",
    archivedOfficialFiles: "File ufficiali archiviati",
    emailUncertain: "Esito SMTP incerto: verifica la mancata consegna prima del reinvio.",
    emailUncertainConfirmed: "Ho verificato che il messaggio non è stato consegnato.",
    emailStatus: {
      PENDING: "In attesa",
      SENT: "Inviata",
      FAILED: "Non riuscita",
    } as Record<string, string>,
    email: "E-mail",
    emailNotPrepared: "Non preparata",
    prepareResend: "Prepara reinvio",
    officialFileKind: {
      ARUBA_XML: "XML Aruba",
      ARUBA_P7M: "P7M",
      ARUBA_PDF: "PDF Aruba",
      SDI_NOTIFICATION: "Notifica SdI",
    } as Record<string, string>,
    manualBatchTitle: "Prepara documenti già approvati",
    manualBatchHelp:
      "Crea un manifest per i documenti approvati prima dell’attivazione dell’helper.",
    manualBatchCount: (count: number) =>
      `${count} ${count === 1 ? "documento da preparare" : "documenti da preparare"}`,
    createBatch: "Crea batch Aruba",
    helperCodeTitle: "Codice di avvio helper",
    helperCodeHelp: (expiresAt: string) =>
      `Incollalo nel prompt dell’helper entro ${expiresAt}. Non salvarlo e non inserirlo nella riga di comando.`,
    batchesTitle: "Batch Aruba",
    batchesHelp:
      "Ogni batch resta legato ai documenti, alle revisioni e agli hash approvati. Uno stato incerto richiede readback.",
    batchesCount: (count: number) => `${count} ${count === 1 ? "batch" : "batch"}`,
    batchCreatedAt: "Creato",
    batchLastReadback: "Ultimo readback",
    batchNeverRead: "Non ancora eseguito",
    batchActions: "Azioni batch",
    batchSummary: (count: number, mode: string) =>
      `${count} ${count === 1 ? "documento" : "documenti"} · ${mode === "AUTOMATIC" ? "Automatica dopo conferma" : "Assistita"}`,
    lastReadback: (value: string) => `ultimo readback ${value}`,
    issueHelperCode: "Genera codice di avvio",
    authorizePermit: "Autorizza nuovo permesso monouso",
    retryBatch: "Prepara nuovo tentativo",
    arubaBatchStatus: {
      PREPARED: "Preparato",
      HELPER_ACTIVE: "Helper attivo",
      VALIDATION_FAILED: "Validazione non riuscita",
      READY_ASSISTED: "Validato; arrestato prima dell’invio",
      PERMIT_CONSUMED: "Permesso consumato",
      SUBMITTED: "Inviato",
      RECONCILIATION_REQUIRED: "Readback necessario",
      RECONCILED: "Riconciliato",
      CANCELLED: "Annullato",
    } as Record<string, string>,
    empty: "Nessun documento",
    emptyHelp: "Le bozze compaiono dopo il primo salvataggio della preparazione.",
    noResults: "Nessun documento corrisponde ai filtri",
    openOrders: "Vai agli ordini",
  },
  activity: {
    eyebrow: "Controlli e cronologia",
    title: "Attività",
    intro: "Vedi subito cosa richiede attenzione e consulta le operazioni già registrate.",
    viewsLabel: "Viste attività",
    toManage: "Da gestire",
    history: "Cronologia",
    nothingToManage: "Niente da gestire",
    nothingToManageHelp: "Nessuna preparazione o operazione dei canali richiede attenzione.",
    overviewLabel: "Riepilogo delle attività da gestire",
    attentionCount: (count: number) =>
      `${count} ${count === 1 ? "attività richiede" : "attività richiedono"} attenzione`,
    attentionHelp: "Le attività sono ordinate dalla più recente e portano al punto da risolvere.",
    reviewsCount: "Verifiche",
    failedJobsCount: "Operazioni non riuscite",
    openHistory: "Apri la cronologia",
    openConnections: "Controlla le connessioni",
    jobRetried: "Operazione del canale riavviata.",
    failedJobsTitle: "Operazioni non riuscite",
    failedJobsHelp: "Sincronizzazioni interrotte che possono essere riavviate in sicurezza.",
    failedJobTitle: (type: string) => connectorJobLabels[type] ?? "Operazione del canale",
    failedJob: (code: string | null, attempts: number) =>
      `${errorCodeLabel(code)} · ${attempts} ${attempts === 1 ? "tentativo" : "tentativi"}`,
    retryJob: "Riprova ora",
    reviewTitle: "Verifiche su ordini e documenti",
    creditNotesFilter: (count: number) =>
      `${count} ${count === 1 ? "nota di credito da approvare" : "note di credito da approvare"}`,
    clearFilters: "Azzera filtro",
    reviewHelp: "Ordini, preparazioni e rimborsi che richiedono una decisione operativa.",
    item: "Elemento",
    customer: "Cliente",
    taxIdentifier: "Identificativo fiscale",
    customerToVerify: "Cliente da verificare",
    channelOrType: "Canale / tipo",
    preparationKind: "Preparazione",
    orderDate: "Data ordine",
    lastUpdated: "Ultimo aggiornamento",
    actions: "Azioni",
    error: "Errore",
    attempts: "Tentativi",
    failedAt: "Non riuscita",
    openItem: "Apri dettaglio",
    openActivityReasons: {
      BILLING_CASE_REVIEW: "Preparazione da verificare",
      HISTORY_RECONCILIATION: "Storico da riconciliare",
      ARUBA_INVOICE_LINK: "Fattura Aruba da collegare",
      ORDER_REVIEW: "Ordine da verificare",
      REFUND_REVIEW: "Rimborso da verificare",
      REFUND_JOB_FAILED: "Rimborso non elaborato",
      CREDIT_NOTE_APPROVAL: "Nota di credito da approvare",
    } as Record<string, string>,
    errorDetail: (code: string | null) => errorCodeLabel(code),
    searchLabel: "Cerca nel registro",
    search: "Cerca",
    searchPlaceholder: "Numero ordine, preparazione o motivo",
    type: "Tipo di attività",
    all: "Tutte",
    filter: "Filtra",
    creditNoteKind: "Nota di credito",
    historyTitle: "Registro attività",
    historyHelp: "Operazioni registrate in ordine cronologico e non modificabili.",
    historyCount: (count: number) =>
      `${count} ${count === 1 ? "risultato" : "risultati"} in questa pagina`,
    reason: "Motivo",
    activity: "Attività",
    subject: "Elemento",
    author: "Autore",
    when: "Quando",
    system: "Sistema",
    recorded: "Attività registrata",
    noHistory: "Nessuna attività registrata",
    noHistoryHelp: "Modifica i filtri oppure attendi la prossima operazione.",
    preparation: (number: string) => `Preparazione fattura ${number}`,
    preparationShort: (number: string) => `Preparazione ${number}`,
    order: (provider: string, number: string) => `${provider} ${number}`,
    refund: (provider: string, number: string) => `Rimborso · ${provider} ${number}`,
    settings: "Impostazioni",
  },
  settings: {
    eyebrow: "Configurazione personale e operativa",
    title: "Impostazioni",
    intro: "Gestisci account, fatturazione, collegamenti e servizi da un’unica pagina.",
    sectionsLabel: "Sezioni delle impostazioni",
    goToSection: "Vai alla sezione",
    profileTitle: "Profilo e sicurezza",
    profileHelp:
      "Rivedi identità, permessi e tema del menu rapido, poi proteggi l’accesso al tuo account.",
    passwordChanged: "Password aggiornata. Le altre sessioni sono state disconnesse.",
    sessionsRevoked: "Le altre sessioni sono state disconnesse.",
    appearanceTitle: "Aspetto",
    passwordTitle: "Password",
    passwordHelp:
      "Usa da 8 a 128 caratteri. Dopo il cambio resterà attiva soltanto questa sessione.",
    currentPassword: "Password attuale",
    newPassword: "Nuova password",
    passwordConfirmation: "Conferma nuova password",
    changePassword: "Aggiorna password",
    sessionsTitle: "Sessioni attive",
    sessionsHelp:
      "Ogni accesso resta valido per un anno ed è indipendente dagli altri dispositivi. Sono mostrate solo informazioni affidabili: Hub Fatture non deduce dispositivo o posizione.",
    currentSession: "Questa sessione",
    otherSession: "Altra sessione",
    lastActivity: (value: string) => `Ultima attività: ${value}`,
    sessionExpiry: (value: string) => `Scade: ${value}`,
    revokeOtherSessions: "Disconnetti le altre sessioni",
    noOtherSessions: "Non risultano altre sessioni attive.",
    exitTitle: "Uscita",
    exitHelp: "Termina questa sessione e torna alla schermata di accesso.",
    billingTitle: "Fatturazione",
    billingHelp: "Definisci quando un ordine diventa una preparazione fattura.",
    saved: "Impostazione aggiornata. Gli ordini in attesa sono stati ricontrollati.",
    preparationHelp:
      "La modifica vale per gli ordini non ancora inseriti in una preparazione. Quelli già pronti non cambiano.",
    preparationLabel: "Prepara la fattura",
    preparationSave: "Salva regola di preparazione fattura",
    onPaid: "Quando il pagamento è confermato",
    onFulfilled: "Quando l’ordine è completamente spedito",
    shopifyPaymentFeeModeLabel: "Commissioni Shopify Payments",
    shopifyPaymentFeeDeduct: "Sottrai la commissione effettiva dal totale fatturabile",
    shopifyPaymentFeeInclude: "Mantieni il totale ordine al lordo della commissione",
    shopifyPaymentFeeModeHelp:
      "Vale solo per pagamenti Shopify Payments e usa la commissione effettiva restituita da Shopify. PayPal, bonifico, PostePay e altri metodi restano sempre al totale pieno. La modifica aggiorna ordini e bozze ancora modificabili; documenti già approvati e storico già riconciliato non cambiano.",
    shopifyPaymentFeeModeSaved:
      "Regola Shopify Payments aggiornata. Ordini e bozze ancora modificabili sono stati ricalcolati.",
    shopifyPaymentFeeModeSave: "Salva regola commissioni Shopify Payments",
    save: "Salva impostazione",
    saveShort: "Salva",
    fiscalTitle: "Profilo fiscale",
    fiscalHelp:
      "Consulta la configurazione fiscale attiva. Le modifiche richiedono un nuovo audit e una nuova versione.",
    fiscalStatus: "Stato",
    fiscalVerified: "Verificato",
    fiscalMock: "Sintetico",
    fiscalVersion: "Versione",
    fiscalRegime: "Regime fiscale",
    fiscalNature: "Natura IVA",
    fiscalSeries: "Serie",
    fiscalCadence: "Numerazione",
    fiscalAnnual: "Annuale",
    fiscalScope: "Ambito contatore",
    fiscalShared: "Condiviso tra fatture e note di credito",
    fiscalLastAudit: "Ultimo audit",
    fiscalMissing: "Il profilo fiscale attivo non è ancora configurato.",
    connectionsTitle: "Connessioni",
    connectionsHelp: "Collega i canali di vendita e controlla gli ultimi aggiornamenti ricevuti.",
    salesChannel: "Canale di vendita",
    providerLabels: {
      SHOPIFY: "Shopify",
      EBAY: "eBay",
    } as Record<"SHOPIFY" | "EBAY", string>,
    connectionEnvironment: "Ambiente",
    connectionAccount: "Account",
    lastCheck: "Ultimo controllo",
    openActivities: "Apri Attività",
    connect: "Collega",
    reconnect: "Ricollega",
    preview: "Controlla intervallo",
    historyStart: (provider: string) => `Importa ordini ${provider} dal`,
    historyHelp: "Gli ordini importati restano bloccati finché non vengono confrontati con Aruba.",
    importHistory: "Importa storico",
    historyTitle: "Importazione iniziale",
    historyComplete: "Completata",
    historyToComplete: "Da completare",
    historyConnectFirst: "Collega il canale per configurare l’importazione iniziale.",
    historyReady: "Import iniziale completato. Gli aggiornamenti automatici sono attivi.",
    connected: "Collegato",
    notConnected: "Non collegato",
    lastSync: "Ultima sincronizzazione",
    never: "Mai",
    previewResult: (provider: string, count: string, review: string) =>
      `${provider}: ${count} ordini nell’anteprima; ${review} con rimborsi da controllare. Nessun ordine è stato importato.`,
    historyImportResult: (provider: string, imported: string, updated: string, ignored: string) =>
      `${provider}: storico importato. Nuovi: ${imported}; aggiornati: ${updated}; meno recenti ignorati: ${ignored}.`,
    ebayHistoryStatus: (history: {
      status: string;
      mode: string;
      count: number;
      reviewRequired: number;
      imported: number;
      updated: number;
      ignored: number;
      errorCode: string | null;
    }) =>
      history.status === "COMPLETED" && history.mode === "IMPORT"
        ? `eBay: storico importato. Nuovi: ${history.imported}; aggiornati: ${history.updated}; meno recenti ignorati: ${history.ignored}.`
        : history.status === "COMPLETED"
          ? `eBay: ${history.count} ordini nell’anteprima; ${history.reviewRequired} con rimborsi da controllare. Nessun ordine è stato importato.`
          : history.status === "FAILED"
            ? `${history.mode === "IMPORT" ? "L’import" : "L’anteprima"} eBay non è riuscita (${errorCodeLabel(history.errorCode)}).`
            : `${history.mode === "IMPORT" ? "Import" : "Anteprima"} eBay in elaborazione. Ricarica la pagina tra poco.`,
    connectionError: (code: string) => `Ultimo errore: ${errorCodeLabel(code)}`,
    customerEmailTitle: "E-mail al cliente",
    customerEmailHelp:
      "Un solo servizio e-mail invia la copia soltanto dopo un esito SdI che conferma l’emissione.",
    customerEmailMode: "Modalità invio copia",
    customerEmailModeHelp:
      "Scegli se inviare automaticamente la copia dopo l’esito SdI o richiedere una conferma prima dell’invio.",
    customerEmailAutomatic: "Automatica dopo l’esito SdI",
    customerEmailManual: "Manuale con approvazione",
    customerEmailSave: "Salva modalità e-mail",
    customerEmailSaved: "Modalità e-mail aggiornata.",
    customerEmailOwnerOnly: "Solo il titolare può cambiare la modalità e-mail.",
    smtpTransport: "Servizio di invio",
    smtpSender: "Mittente",
    smtpStatus: "Configurazione",
    smtpConfigured: "Configurato",
    smtpNotConfigured: "Da completare",
    smtpTransportLabels: {
      SYNTHETIC: "Sintetico, senza rete",
      EXISTING_SMTP: "SMTP esistente",
      OCI_EMAIL_DELIVERY: "OCI Email Delivery",
    } as Record<string, string>,
    arubaTitle: "Integrazione Aruba",
    arubaHelp:
      "L’helper usa Chrome o Edge sul tuo computer. Hub Fatture non conserva credenziali, cookie o codici Aruba.",
    arubaMode: "Modalità Aruba",
    arubaAssisted: "Assistita",
    arubaAutomatic: "Automatica dopo conferma",
    arubaAuthProtection: "Protezione dichiarata",
    arubaAuthUnknown: "Da verificare",
    arubaTwoFactor: "2FA attiva",
    arubaSms: "SMS richiesto a ogni caricamento",
    arubaSaved: "Impostazioni Aruba aggiornate.",
    arubaSave: "Salva integrazione Aruba",
    arubaOwnerOnly: "Solo il titolare può cambiare la modalità Aruba.",
    arubaKillSwitch:
      "Gli invii automatici operativi sono disabilitati: i nuovi batch useranno la modalità assistita.",
    arubaConfiguredMode: "Modalità configurata",
    arubaEffectiveMode: "Modalità effettiva",
    arubaModeLabel: (value: string) =>
      value === "AUTOMATIC" ? "Automatica dopo conferma" : "Assistita",
    helperLastSeen: "Ultimo contatto helper",
    helperVersion: "Versione helper",
    helperBrowser: "Browser helper",
    helperLastReadback: "Ultimo readback",
    systemTitle: "Sistema",
    systemHelp: "Controlla i parametri generali che influenzano tutta l’applicazione.",
    systemOperations: "Operatività",
    systemData: "Dati e backup",
    systemTechnical: "Dettagli tecnici",
    environment: "Ambiente applicativo",
    environmentLabel: (value: string) =>
      value === "production" ? "Produzione" : value === "test" ? "Test" : "Sviluppo",
    timeZone: "Fuso orario",
    applicationVersion: "Versione applicativa",
    commit: "Commit distribuito",
    imageDigest: "Digest immagine",
    databaseSchema: "Schema database",
    workerQueue: "Coda operativa",
    workerQueueStatus: (active: number, failed: number) =>
      `${active} in corso o in attesa; ${failed} non riusciti.`,
    arubaKillSwitchStatus: "Invio automatico Aruba",
    enabled: "Abilitato",
    disabled: "Disabilitato",
    lastBackup: "Ultimo backup verificato",
    backupStatus: (completedAt: string, sizeBytes: number) =>
      `${completedAt} · ${integerFormatter.format(sizeBytes)} byte`,
    backupPending: "Nessuna ricevuta valida disponibile",
    systemOperationalHelp:
      "Questi valori sono riletti dall’applicazione, dal database e dalla ricevuta dell’ultimo backup.",
  },
  customerEditor: {
    title: "Dati del destinatario",
    intro:
      "Le modifiche valgono per questa preparazione. I dati ricevuti dal canale di vendita restano consultabili nel dettaglio dell’ordine.",
    identity: "Cliente",
    address: "Indirizzo di fatturazione",
    tax: "Dati fiscali",
    kind: "Tipo destinatario",
    displayName: "Nome da mostrare",
    firstName: "Nome",
    lastName: "Cognome",
    companyName: "Ragione sociale",
    phone: "Telefono",
    email: "E-mail",
    certifiedEmail: "PEC",
    recipientCode: "Codice destinatario SdI",
    line1: "Indirizzo",
    line2: "Indirizzo, seconda riga",
    postalCode: "CAP",
    city: "Città",
    province: "Provincia",
    country: "Paese",
    countryHelp: "Usa due lettere, per esempio IT per Italia.",
    identifier: (number: number) => `Dato fiscale ${number}`,
    newIdentifier: "Nuovo dato fiscale",
    type: "Tipo",
    value: "Valore",
    emptyRemoves: "Lascia vuoto per rimuoverlo.",
    reason: "Motivo della correzione",
    save: "Salva dati cliente",
  },
  pager: {
    label: "Paginazione",
    previous: "Pagina precedente",
    next: "Pagina successiva",
    current: (page: number) => `Pagina ${page}`,
  },
  theme: {
    label: "Tema",
    system: "Sistema",
    light: "Chiaro",
    dark: "Scuro",
  },
  error: {
    eyebrow: "Errore",
    notFound: "La pagina non esiste",
    unexpected: "La richiesta non è andata a buon fine",
    notFoundHelp:
      "L’indirizzo potrebbe essere errato oppure la pagina potrebbe essere stata spostata.",
    unexpectedHelp: "Si è verificato un problema inatteso durante l’apertura della pagina.",
    action: "Torna alla dashboard per continuare.",
    home: "Torna alla dashboard",
  },
  arubaSynthetic: {
    eyebrow: "Simulatore locale",
    title: "Carica fatture da inviare",
    intro: "Ambiente sintetico: nessun documento viene trasmesso ad Aruba.",
    account: (reference: string) => `Account ${reference}`,
    uploadTitle: "Documenti da verificare",
    uploadHelp: "Seleziona uno o più XML FatturaPA e controllane l’esito prima dell’invio.",
    selectDocuments: "Seleziona documenti",
    browseDocuments: "Scegli XML",
    noDocumentsSelected: "Nessun documento selezionato",
    selectedDocuments: (count: number) =>
      `${count} ${count === 1 ? "documento selezionato" : "documenti selezionati"}`,
    uploadedDocuments: "Documenti caricati",
    file: "File",
    validation: "Validazione",
    action: "Azione",
    valid: "Documento valido",
    invalid: "Dettagli errori",
    sent: "Inviato · ID Aruba: MOCK-001",
    download: "Scarica XML",
    remove: "Rimuovi",
    invalidNotice: "Uno o più documenti contengono errori.",
    acquired: "Documenti acquisiti · MOCK-001",
    uncertain: "Stato non disponibile",
    send: "Invia",
    saveDrafts: "Salva in bozze",
    loginTitle: "Accesso richiesto",
    loginHelp: "Completa manualmente password, OTP o CAPTCHA. L’helper resta in pausa.",
    loginAction: "Autenticazione completata",
    unexpectedTitle: "Pagina non riconosciuta",
    unexpectedHelp: "L’helper ha incontrato una schermata diversa da quelle previste.",
    backToSimulator: "Torna al simulatore",
    otpQuestion: "Vuoi disattivare la protezione OTP su Carica Fatture?",
    continue: "Prosegui",
    verificationTitle: "Verifica",
    smsCode: "Inserisci il codice ricevuto per SMS",
    verify: "Verifica",
  },
} as const;

export const orderStatusLabels: Record<string, string> = {
  WAITING_FOR_TRIGGER: "In attesa di pagamento o spedizione",
  ELIGIBLE: "Da preparare",
  GROUPED: "Fattura in preparazione",
  CANCELLED_NO_DOCUMENT: "Annullato, nessuna fattura",
  REFUNDED_BEFORE_ISSUE: "Rimborsato, nessuna fattura",
  INVOICED: "Fatturato",
  NEEDS_REVIEW: "Da verificare",
  LEGACY_BILLING_REVIEW: "Storico da riconciliare",
};

export const orderListStatusLabels: Record<string, string> = {
  WAITING_FOR_TRIGGER: "In attesa",
  ELIGIBLE: "Da preparare",
  GROUPED: "In preparazione",
  CANCELLED_NO_DOCUMENT: "Annullato",
  REFUNDED_BEFORE_ISSUE: "Rimborsato",
  INVOICED: "Fatturato",
  NEEDS_REVIEW: "Da verificare",
  LEGACY_BILLING_REVIEW: "Da riconciliare",
};

export const paymentStatusLabels: Record<string, string> = {
  PAID: "Pagato",
  PENDING: "In attesa",
  REFUNDED: "Rimborsato",
};

export const refundStatusLabels: Record<string, string> = {
  PENDING: "In attesa",
  COMPLETED: "Completato",
  FAILED: "Non riuscito",
  AMBIGUOUS: "Da verificare",
};

export const fulfillmentStatusLabels: Record<string, string> = {
  FULFILLED: "Spedito",
  PARTIAL: "Spedito in parte",
  UNFULFILLED: "Non ancora spedito",
};

export const customerKindLabels: Record<string, string> = {
  PRIVATE_IT: "Privato italiano",
  BUSINESS_IT: "Azienda italiana",
  EU: "Cliente UE",
  UNKNOWN: "Tipo da verificare",
};

export const customerMatchLabels: Record<string, string> = {
  TAX_ID: "codice fiscale o partita IVA",
  EXACT_PROFILE: "nome, indirizzo ed e-mail",
  AMBIGUOUS: "dati da verificare",
};

export const taxIdentifierLabels: Record<string, string> = {
  CODICE_FISCALE: "Codice fiscale",
  PARTITA_IVA: "Partita IVA",
  ALTRO: "Altro dato fiscale",
};

export const auditActionLabels = {
  ACCOUNT_PASSWORD_CHANGED: "Password dell’account aggiornata",
  ACCOUNT_SESSIONS_REVOKED: "Altre sessioni disconnesse",
  ADMIN_ACCOUNT_CREATED: "Account amministrativo creato",
  ARUBA_ASSISTED_STOPPED: "Helper arrestato prima dell’invio",
  ARUBA_BATCH_CREATED: "Batch Aruba creato",
  ARUBA_FILE_IMPORTED: "File Aruba importato",
  ARUBA_HELPER_TOKEN_CREATED: "Codice helper generato",
  ARUBA_READBACK_RECONCILED: "Readback Aruba riconciliato",
  ARUBA_RECONCILIATION_REQUIRED: "Riconciliazione Aruba richiesta",
  ARUBA_SEND_PERMIT_CONSUMED: "Permesso Aruba consumato",
  ARUBA_SEND_PERMIT_CREATED: "Permesso Aruba creato",
  ARUBA_SETTINGS_CHANGED: "Impostazioni Aruba modificate",
  ARUBA_UPLOAD_VALIDATED: "Caricamento Aruba validato",
  ARUBA_VALIDATION_FAILED: "Validazione Aruba non riuscita",
  BILLING_CASE_CREATED: "Preparazione fattura creata",
  BILLING_CASE_DO_NOT_TRANSMIT: "Preparazione chiusa senza trasmissione",
  BILLING_CASE_REACTIVATED: "Preparazione riattivata",
  CUSTOMER_CORRECTED: "Anagrafica cliente corretta",
  CUSTOMER_EMAIL_FAILED: "Invio e-mail non riuscito",
  CUSTOMER_EMAIL_QUEUED: "Invio e-mail preparato",
  CUSTOMER_EMAIL_REQUEUED: "Reinvio e-mail preparato",
  CUSTOMER_EMAIL_SENT: "E-mail inviata",
  CUSTOMER_EMAIL_SETTINGS_CHANGED: "Modalità e-mail aggiornata",
  DRAFT_TRIGGER_CHANGED: "Regola di preparazione modificata",
  SHOPIFY_PAYMENT_FEE_MODE_CHANGED: "Regola commissioni Shopify Payments modificata",
  DOCUMENT_APPROVED: "Documento approvato",
  DOCUMENT_AMOUNT_DIFFERENCE_CONFIRMED: "Differenza d’importo confermata",
  DOCUMENT_DRAFT_SAVED: "Bozza fiscale salvata",
  DOCUMENT_NUMBERED: "Numero fiscale assegnato",
  DOCUMENT_PENDING_PAYMENT_CONFIRMED: "Pagamento pendente confermato",
  FISCAL_PROFILE_ACTIVATED: "Profilo fiscale approvato",
  LOGIN_FAILED: "Accesso rifiutato",
  LOGIN_RATE_LIMITED: "Accessi temporaneamente bloccati",
  LOGIN_SUCCEEDED: "Accesso riuscito",
  LOGOUT_SUCCEEDED: "Uscita registrata",
  ORDER_GROUPED: "Ordine aggiunto alla preparazione",
  ORDER_GROUPING_FORCED: "Preparazione anticipata richiesta",
  ORDER_HISTORY_RECONCILED: "Storico confrontato con Aruba",
  ORDER_IMPORTED: "Ordine importato",
  ORDER_SEPARATED: "Ordine separato dalla preparazione",
  ORDER_SOURCE_CONFLICT: "Aggiornamento dell’ordine da verificare",
  ORDER_SOURCE_REVIEWED: "Aggiornamento dell’ordine verificato",
  ORDER_SOURCE_UPDATED: "Ordine aggiornato dal canale di vendita",
  PROVIDER_CONNECTED: "Canale di vendita collegato",
  PROVIDER_REVOKED: "Canale di vendita scollegato",
  REFUND_APPLIED_BEFORE_ISSUE: "Rimborso applicato prima dell’emissione",
  REFUND_REVERSED_BEFORE_ISSUE: "Rimborso ripristinato prima dell’emissione",
  REFUND_CREDIT_NOTE_LINKED: "Rimborso collegato alla nota di credito",
  REFUND_CREDIT_NOTE_UPDATED: "Nota di credito aggiornata dal rimborso",
  REFUND_NEEDS_REVIEW: "Rimborso da verificare",
  CONNECTOR_JOB_RETRIED: "Operazione del canale riavviata",
  SHOPIFY_DATA_REQUEST_COMPLETED: "Richiesta dati Shopify gestita",
} satisfies Record<AuditAction, string>;

export function auditActionLabel(action: string) {
  return (auditActionLabels as Record<string, string>)[action];
}

export const billingCaseStatusLabels: Record<string, string> = {
  DRAFT: "In lavorazione",
  NEEDS_REVIEW: "Da verificare",
  READY: "Pronta",
  DO_NOT_TRANSMIT: "Da non trasmettere",
  APPROVED: "Approvata",
  CLOSED: "Chiusa",
};

/** Ogni anomalia dichiara il fatto osservato e l'azione che la chiude (13.10). */
export const anomalyLabels: Record<string, { title: string; action: string }> = {
  PENDING_PAYMENT: {
    title: "Pagamento non ancora acquisito",
    action:
      "Attendi l’incasso oppure registralo nella bozza fiscale senza modificare il canale di vendita.",
  },
  TOTALS_MISMATCH: {
    title: "Totale dell\u2019ordine non riconciliato",
    action:
      "Articoli, spedizione e pagamenti non ricostruiscono il totale ricevuto: verifica l’ordine sul canale di vendita.",
  },
  CUSTOMER_INCOMPLETE: {
    title: "Anagrafica fiscale incompleta",
    action: "Completa i dati del cliente in questa pagina.",
  },
  CUSTOMER_MISMATCH: {
    title: "Anagrafiche discordanti fra gli ordini",
    action: "Correggi l\u2019anagrafica della preparazione oppure separa l\u2019ordine incoerente.",
  },
  SOURCE_CONFLICT: {
    title: "L’ordine è cambiato dopo la preparazione",
    action: "Confronta le versioni conservate qui sotto prima di proseguire.",
  },
  ORDER_NOT_BILLABLE: {
    title: "Ordine annullato o rimborsato",
    action: "Separa l\u2019ordine oppure archivia la preparazione con “Non trasmettere”.",
  },
};

export const reactivationBlockerMessages: Record<string, string> = {
  EMPTY:
    "Questa preparazione storica non contiene più ordini e resta consultabile soltanto in archivio.",
  INCOMPATIBLE_ORDERS:
    "Gli ordini sono ancora annullati o rimborsati. La preparazione resta in archivio finché il canale di vendita non li rettifica.",
  OTHER_OPEN_CASE:
    "Esiste già un’altra preparazione aperta per lo stesso cliente e giorno. Questa resta in archivio.",
};
