export const documentArubaSearchCopy = {
  lookupBy: "Cerca per",
  lookupValue: "Identificativo",
  verifyOnAruba: "Verifica su Aruba",
  advancedArubaSearch: "Ricerca avanzata sul ciclo attivo Aruba",
  advancedArubaSearchHelp:
    "L’intervallo di ricezione è obbligatorio e non può superare 48 ore. I risultati vengono verificati e acquisiti nell’inventario.",
  creationStart: "Ricevuta da Aruba dal",
  creationEnd: "Ricevuta da Aruba al",
  vatOnly: "Partita IVA destinatario",
  fiscalCodeOnly: "Codice fiscale destinatario",
  providerStatuses: [
    "Presa in carico",
    "Errore elaborazione",
    "Inviata",
    "Scartata",
    "Non consegnata",
    "Recapito impossibile",
    "Consegnata",
    "Accettata",
    "Rifiutata",
    "Decorrenza termini",
  ],
  arubaLookupRequested:
    "Ricerca puntuale accodata. L’inventario si aggiornerà dopo la verifica Aruba.",
  arubaRefreshRequested: "Aggiornamento dello stato Aruba accodato.",
  advancedFilters: "Filtri avanzati",
  remoteUpdatedFrom: "Aggiornato da Aruba dal",
  remoteUpdatedTo: "Aggiornato da Aruba al",
  recipientCountry: "Paese destinatario",
  recipientTaxId: "P. IVA o codice fiscale",
  origin: "Origine",
  allOrigins: "Tutte",
  originLocal: "Creato in questa applicazione",
  originAruba: "Storico Aruba",
  fiscalNumber: "Numero fiscale",
  providerFilename: "Filename Aruba",
  sdiId: "ID SdI",
  refreshArubaStatus: "Aggiorna stato Aruba",
  refreshingArubaStatus: "Aggiornamento richiesto…",
  arubaDetail: "Stato e cronologia Aruba",
  arubaDetailHelp: "Identificativi, letture ed esiti sono separati dalle azioni sul documento.",
  currentArubaStatus: "Stato corrente",
  arubaIdentifiers: "Identificativi",
  arubaTimeline: "Cronologia della trasmissione",
  arubaTimelineEmpty: "La trasmissione non ha ancora prodotto eventi remoti.",
  arubaLastStatusChange: "Ultimo cambio di stato",
  arubaLastCheck: "Ultima verifica",
  arubaSource: "Fonte",
  arubaSourceLabels: {
    ARUBA: "Aruba",
    SDI: "SdI",
  } as Record<string, string>,
  arubaActions: "Azioni disponibili",
  arubaNoIdentifiers: "Gli identificativi remoti non sono ancora disponibili.",
  advancedArubaPrimaryGroup: "Intervallo Aruba",
  advancedArubaRecipientGroup: "Destinatario",
  advancedArubaDocumentGroup: "Documento ed esito",
  searchArubaPending: "Ricerca in accodamento…",
  remoteResults: (count: number) =>
    `${count} ${count === 1 ? "documento Aruba trovato" : "documenti Aruba trovati"}`,
  noRemoteSearchResults: (query: string) =>
    `Nessun documento dell’inventario Aruba corrisponde a “${query}”.`,
};

export const arubaTransmissionStatusCopy = {
  SEND_PENDING: "Trasmissione Aruba pianificata",
  SEND_FAILED: "Trasmissione rifiutata da Aruba",
  ARUBA_ACCEPTED: "Accettato da Aruba; esito SdI in attesa",
};
