import { index, route, type RouteConfig } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("health", "routes/health.ts"),
  route("integrations/shopify/auth", "routes/shopify-auth.ts"),
  route("integrations/shopify/callback", "routes/shopify-callback.ts"),
  route("integrations/ebay/auth", "routes/ebay-auth.ts"),
  route("integrations/ebay/callback", "routes/ebay-callback.ts"),
  route("webhooks/shopify", "routes/shopify-webhook.ts"),
  route("webhooks/ebay/account-deletion", "routes/ebay-account-deletion.ts"),
  route("login", "routes/login.tsx"),
  route("logout", "routes/logout.ts"),
  route("ordini", "routes/orders.tsx"),
  route("ordini/preparazione/:caseId", "routes/billing-case-detail.tsx"),
  route("ordini/:orderId", "routes/order-detail.tsx"),
  route("clienti/:customerId", "routes/customer-detail.tsx"),
  route("documenti", "routes/documents.tsx"),
  route("documenti/:documentId/nota", "routes/credit-note-detail.tsx"),
  route("documenti/:documentId/xml", "routes/document-xml.ts"),
  route("documenti/:documentId/aruba/:fileId", "routes/aruba-official-file.ts"),
  route("api/aruba/helper/manifest", "routes/aruba-helper-manifest.ts"),
  route("api/aruba/helper/documenti/:documentId/xml", "routes/aruba-helper-document.ts"),
  route("api/aruba/helper/documenti/:documentId/file", "routes/aruba-helper-file.ts"),
  route("api/aruba/helper/eventi", "routes/aruba-helper-events.ts"),
  route("api/aruba/helper/consuma-permesso", "routes/aruba-helper-permit.ts"),
  route("aruba-sintetica", "routes/aruba-synthetic.tsx"),
  route("attivita", "routes/activity.tsx"),
  route("ricerca", "routes/search.ts"),
  route("impostazioni", "routes/settings.tsx"),
  route("setup", "routes/setup.tsx"),
] satisfies RouteConfig;
