import { index, route, type RouteConfig } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("robots.txt", "routes/robots.ts"),
  route("manifest.webmanifest", "routes/manifest.ts"),
  route("health", "routes/health.ts"),
  route("api/profilo-fiscale", "routes/fiscal-profile-api.ts"),
  route("integrations/shopify/auth", "routes/shopify-auth.ts"),
  route("integrations/shopify/callback", "routes/shopify-callback.ts"),
  route("integrations/ebay/auth", "routes/ebay-auth.ts"),
  route("integrations/ebay/callback", "routes/ebay-callback.ts"),
  route("webhooks/shopify", "routes/shopify-webhook.ts"),
  route("webhooks/ebay/account-deletion", "routes/ebay-account-deletion.ts"),
  route("login", "routes/login.tsx"),
  route("logout", "routes/logout.ts"),
  route("ordini", "routes/orders.tsx"),
  route("ordini/candidati-approvazione", "routes/order-approval-candidates.ts"),
  route("ordini/preparazione/:caseId", "routes/billing-case-detail.tsx"),
  route("ordini/:orderId", "routes/order-detail.tsx"),
  route("documenti", "routes/documents.tsx"),
  route("documenti/:documentId/nota", "routes/credit-note-detail.tsx"),
  route("documenti/:documentId/xml", "routes/document-xml.ts"),
  route("documenti/:documentId/aruba/:fileId", "routes/aruba-official-file.ts"),
  route("clienti", "routes/customers.tsx"),
  route("clienti/:customerId", "routes/customer-detail.tsx"),
  route("controlli", "routes/controls.tsx"),
  route("attivita", "routes/activity.tsx"),
  route("ricerca", "routes/search.ts"),
  route("impostazioni", "routes/settings.tsx"),
  route("setup", "routes/setup.tsx"),
] satisfies RouteConfig;
